/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspLbModeC_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspLbModeC_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspLbModeC_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspLbModeC_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspLbModeC_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFixedBaseEnable(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_fixedBaseEnable_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getFixedBaseEnable() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_fixedBaseEnable_get(swigCPtr, this), true);
  }

  public void setAutoSurveyEnable(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_autoSurveyEnable_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getAutoSurveyEnable() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_autoSurveyEnable_get(swigCPtr, this), true);
  }

  public void setConnected(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_connected_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getConnected() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_connected_get(swigCPtr, this), true);
  }

  public void setCorrectionOutput(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_correctionOutput_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getCorrectionOutput() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_correctionOutput_get(swigCPtr, this), true);
  }

  public void setCorrectionInput(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_correctionInput_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getCorrectionInput() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_correctionInput_get(swigCPtr, this), true);
  }

  public void setTripodCorrections(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_tripodCorrections_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getTripodCorrections() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_tripodCorrections_get(swigCPtr, this), true);
  }

  public void setValidOrNotBusy(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_validOrNotBusy_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getValidOrNotBusy() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_validOrNotBusy_get(swigCPtr, this), true);
  }

  public void setBroadcastEnable(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspLbModeC_t_broadcastEnable_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getBroadcastEnable() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspLbModeC_t_broadcastEnable_get(swigCPtr, this), true);
  }

  public SqspLbModeC_t() {
    this(sqspJNI.new_SqspLbModeC_t(), true);
  }

}
