/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class sqsp {
  public static boolean sqspLbModeCInit(SqspLbModeC_t lbm, char fixedBaseEnable, char autoSurveyEnable, char connected, char correctionOutput, char correctionInput, char tripodCorrections, char validOrNotBusy, char broadcastEnable) {
    return sqspJNI.sqspLbModeCInit(SqspLbModeC_t.getCPtr(lbm), lbm, fixedBaseEnable, autoSurveyEnable, connected, correctionOutput, correctionInput, tripodCorrections, validOrNotBusy, broadcastEnable);
  }

  public static boolean sqspLbModeInit(SqspLbMode_t lbm, char fixedBaseEnable, char autoSurveyEnable, char connected, char correctionOutput, char correctionInput, char tripodCorrections, char validOrNotBusy, char broadcastEnable) {
    return sqspJNI.sqspLbModeInit(SqspLbMode_t.getCPtr(lbm), lbm, fixedBaseEnable, autoSurveyEnable, connected, correctionOutput, correctionInput, tripodCorrections, validOrNotBusy, broadcastEnable);
  }

  public static boolean sqspLbModeExpand(SqspLbMode_t lbm, SqspLbModeC_t lbms) {
    return sqspJNI.sqspLbModeExpand(SqspLbMode_t.getCPtr(lbm), lbm, SqspLbModeC_t.getCPtr(lbms), lbms);
  }

  public static boolean sqspLbModeCompact(SqspLbModeC_t lbm, SqspLbMode_t lbms) {
    return sqspJNI.sqspLbModeCompact(SqspLbModeC_t.getCPtr(lbm), lbm, SqspLbMode_t.getCPtr(lbms), lbms);
  }

  public static boolean sqspLbConfigCInit(SqspLbConfigC_t lbc, SWIGTYPE_p_int32_t lon, SWIGTYPE_p_int32_t lat, SWIGTYPE_p_int32_t height, SWIGTYPE_p_uint32_t hAcc, SWIGTYPE_p_uint32_t vAcc, SWIGTYPE_p_int8_t lonHp, SWIGTYPE_p_int8_t latHp, SWIGTYPE_p_int8_t heightHp, SqspLbModeC_t mode, SWIGTYPE_p_uint32_t duration, SWIGTYPE_p_int32_t hMSL, SWIGTYPE_p_int8_t hMSLHp) {
    return sqspJNI.sqspLbConfigCInit(SqspLbConfigC_t.getCPtr(lbc), lbc, SWIGTYPE_p_int32_t.getCPtr(lon), SWIGTYPE_p_int32_t.getCPtr(lat), SWIGTYPE_p_int32_t.getCPtr(height), SWIGTYPE_p_uint32_t.getCPtr(hAcc), SWIGTYPE_p_uint32_t.getCPtr(vAcc), SWIGTYPE_p_int8_t.getCPtr(lonHp), SWIGTYPE_p_int8_t.getCPtr(latHp), SWIGTYPE_p_int8_t.getCPtr(heightHp), SqspLbModeC_t.getCPtr(mode), mode, SWIGTYPE_p_uint32_t.getCPtr(duration), SWIGTYPE_p_int32_t.getCPtr(hMSL), SWIGTYPE_p_int8_t.getCPtr(hMSLHp));
  }

  public static boolean sqspLbConfigInit(SqspLbConfig_t lbc, double lon, double lat, double height, double hMSL, double hAcc, double vAcc, SWIGTYPE_p_uint32_t duration, SqspLbMode_t mode) {
    return sqspJNI.sqspLbConfigInit(SqspLbConfig_t.getCPtr(lbc), lbc, lon, lat, height, hMSL, hAcc, vAcc, SWIGTYPE_p_uint32_t.getCPtr(duration), SqspLbMode_t.getCPtr(mode), mode);
  }

  public static boolean sqspLbConfigExpand(SqspLbConfig_t lbc, SqspLbConfigC_t lbcs) {
    return sqspJNI.sqspLbConfigExpand(SqspLbConfig_t.getCPtr(lbc), lbc, SqspLbConfigC_t.getCPtr(lbcs), lbcs);
  }

  public static boolean sqspLbConfigCompact(SqspLbConfigC_t lbc, SqspLbConfig_t lbcs) {
    return sqspJNI.sqspLbConfigCompact(SqspLbConfigC_t.getCPtr(lbc), lbc, SqspLbConfig_t.getCPtr(lbcs), lbcs);
  }

  public static boolean sqspRspCInit(SqspRspC_t rsp, short mfgDataId, char batteryLevel, char systemPowerState, short runTimeRemaining, char satelliteCount, char aidingBins, char differential, char gpsFixOk, char ambiguity, char fix, char coprocOk, char surveyFailed, char surveyPositionValid, char surveyInProgress, char headingFlag, char posValid, char validTime, SqspLbModeC_t mode) {
    return sqspJNI.sqspRspCInit(SqspRspC_t.getCPtr(rsp), rsp, mfgDataId, batteryLevel, systemPowerState, runTimeRemaining, satelliteCount, aidingBins, differential, gpsFixOk, ambiguity, fix, coprocOk, surveyFailed, surveyPositionValid, surveyInProgress, headingFlag, posValid, validTime, SqspLbModeC_t.getCPtr(mode), mode);
  }

  public static boolean sqspRspInit(SqspRsp_t rsp, SWIGTYPE_p_uint16_t mfgDataId, SWIGTYPE_p_uint8_t batteryLevel, SWIGTYPE_p_uint8_t systemPowerState, SWIGTYPE_p_uint16_t runTimeRemaining, SWIGTYPE_p_uint8_t satelliteCount, SWIGTYPE_p_uint8_t aidingBins, SWIGTYPE_p_uint8_t differential, SWIGTYPE_p_uint8_t gpsFixOk, SWIGTYPE_p_uint8_t ambiguity, SWIGTYPE_p_uint8_t fix, SWIGTYPE_p_uint8_t coprocOk, SWIGTYPE_p_uint8_t surveyFailed, SWIGTYPE_p_uint8_t surveyPositionValid, SWIGTYPE_p_uint8_t surveyInProgress, SWIGTYPE_p_uint8_t headingFlag, SWIGTYPE_p_uint8_t posValid, SWIGTYPE_p_uint8_t validTime, SqspLbMode_t mode) {
    return sqspJNI.sqspRspInit(SqspRsp_t.getCPtr(rsp), rsp, SWIGTYPE_p_uint16_t.getCPtr(mfgDataId), SWIGTYPE_p_uint8_t.getCPtr(batteryLevel), SWIGTYPE_p_uint8_t.getCPtr(systemPowerState), SWIGTYPE_p_uint16_t.getCPtr(runTimeRemaining), SWIGTYPE_p_uint8_t.getCPtr(satelliteCount), SWIGTYPE_p_uint8_t.getCPtr(aidingBins), SWIGTYPE_p_uint8_t.getCPtr(differential), SWIGTYPE_p_uint8_t.getCPtr(gpsFixOk), SWIGTYPE_p_uint8_t.getCPtr(ambiguity), SWIGTYPE_p_uint8_t.getCPtr(fix), SWIGTYPE_p_uint8_t.getCPtr(coprocOk), SWIGTYPE_p_uint8_t.getCPtr(surveyFailed), SWIGTYPE_p_uint8_t.getCPtr(surveyPositionValid), SWIGTYPE_p_uint8_t.getCPtr(surveyInProgress), SWIGTYPE_p_uint8_t.getCPtr(headingFlag), SWIGTYPE_p_uint8_t.getCPtr(posValid), SWIGTYPE_p_uint8_t.getCPtr(validTime), SqspLbMode_t.getCPtr(mode), mode);
  }

  public static boolean sqspRspExpand(SqspRsp_t rsp, SqspRspC_t rsps) {
    return sqspJNI.sqspRspExpand(SqspRsp_t.getCPtr(rsp), rsp, SqspRspC_t.getCPtr(rsps), rsps);
  }

  public static boolean sqspRspCompact(SqspRspC_t rsp, SqspRsp_t rsps) {
    return sqspJNI.sqspRspCompact(SqspRspC_t.getCPtr(rsp), rsp, SqspRsp_t.getCPtr(rsps), rsps);
  }

  public static boolean sqspStatusCInit(SqspStatusC_t s, SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_uint16_t year, SWIGTYPE_p_uint8_t month, SWIGTYPE_p_uint8_t day, SWIGTYPE_p_uint8_t hour, SWIGTYPE_p_uint8_t min, SWIGTYPE_p_uint8_t sec, SWIGTYPE_p_uint8_t solType, SWIGTYPE_p_uint8_t numSV, SWIGTYPE_p_uint8_t battery, SqspRspC_t rsp) {
    return sqspJNI.sqspStatusCInit(SqspStatusC_t.getCPtr(s), s, SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_uint16_t.getCPtr(year), SWIGTYPE_p_uint8_t.getCPtr(month), SWIGTYPE_p_uint8_t.getCPtr(day), SWIGTYPE_p_uint8_t.getCPtr(hour), SWIGTYPE_p_uint8_t.getCPtr(min), SWIGTYPE_p_uint8_t.getCPtr(sec), SWIGTYPE_p_uint8_t.getCPtr(solType), SWIGTYPE_p_uint8_t.getCPtr(numSV), SWIGTYPE_p_uint8_t.getCPtr(battery), SqspRspC_t.getCPtr(rsp), rsp);
  }

  public static boolean sqspStatusInit(SqspStatus_t s, SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_uint32_t time, SWIGTYPE_p_uint8_t solType, SWIGTYPE_p_uint8_t numSV, SWIGTYPE_p_uint8_t battery, SqspRsp_t rsp) {
    return sqspJNI.sqspStatusInit(SqspStatus_t.getCPtr(s), s, SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_uint32_t.getCPtr(time), SWIGTYPE_p_uint8_t.getCPtr(solType), SWIGTYPE_p_uint8_t.getCPtr(numSV), SWIGTYPE_p_uint8_t.getCPtr(battery), SqspRsp_t.getCPtr(rsp), rsp);
  }

  public static boolean sqspStatusExpand(SqspStatus_t s, SqspStatusC_t ss) {
    return sqspJNI.sqspStatusExpand(SqspStatus_t.getCPtr(s), s, SqspStatusC_t.getCPtr(ss), ss);
  }

  public static boolean sqspStatusCompact(SqspStatusC_t s, SqspStatus_t ss) {
    return sqspJNI.sqspStatusCompact(SqspStatusC_t.getCPtr(s), s, SqspStatus_t.getCPtr(ss), ss);
  }

  public static boolean sqspRelPosCInit(SqspRelPosC_t rp, SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_int32_t posN, SWIGTYPE_p_int32_t posE, SWIGTYPE_p_int32_t posD, SWIGTYPE_p_int8_t posHpN, SWIGTYPE_p_int8_t posHpE, SWIGTYPE_p_int8_t posHpD) {
    return sqspJNI.sqspRelPosCInit(SqspRelPosC_t.getCPtr(rp), rp, SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_int32_t.getCPtr(posN), SWIGTYPE_p_int32_t.getCPtr(posE), SWIGTYPE_p_int32_t.getCPtr(posD), SWIGTYPE_p_int8_t.getCPtr(posHpN), SWIGTYPE_p_int8_t.getCPtr(posHpE), SWIGTYPE_p_int8_t.getCPtr(posHpD));
  }

  public static boolean sqspRelPosInit(SqspRelPos_t rp, SWIGTYPE_p_uint32_t iTOW, double posN, double posE, double posD) {
    return sqspJNI.sqspRelPosInit(SqspRelPos_t.getCPtr(rp), rp, SWIGTYPE_p_uint32_t.getCPtr(iTOW), posN, posE, posD);
  }

  public static boolean sqspRelPosExpand(SqspRelPos_t rp, SqspRelPosC_t rps) {
    return sqspJNI.sqspRelPosExpand(SqspRelPos_t.getCPtr(rp), rp, SqspRelPosC_t.getCPtr(rps), rps);
  }

  public static boolean sqspRelPosCompact(SqspRelPosC_t rp, SqspRelPos_t rps) {
    return sqspJNI.sqspRelPosCompact(SqspRelPosC_t.getCPtr(rp), rp, SqspRelPos_t.getCPtr(rps), rps);
  }

  public static boolean sqspLlaCInit(SqspLlaC_t lla, SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_int32_t lon, SWIGTYPE_p_int32_t lat, SWIGTYPE_p_int32_t height, SWIGTYPE_p_int8_t lonHp, SWIGTYPE_p_int8_t latHp, SWIGTYPE_p_int8_t heightHp, SWIGTYPE_p_int8_t hMSLHp, SWIGTYPE_p_uint32_t hAcc, SWIGTYPE_p_uint32_t vAcc, SWIGTYPE_p_int32_t hMSL) {
    return sqspJNI.sqspLlaCInit(SqspLlaC_t.getCPtr(lla), lla, SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_int32_t.getCPtr(lon), SWIGTYPE_p_int32_t.getCPtr(lat), SWIGTYPE_p_int32_t.getCPtr(height), SWIGTYPE_p_int8_t.getCPtr(lonHp), SWIGTYPE_p_int8_t.getCPtr(latHp), SWIGTYPE_p_int8_t.getCPtr(heightHp), SWIGTYPE_p_int8_t.getCPtr(hMSLHp), SWIGTYPE_p_uint32_t.getCPtr(hAcc), SWIGTYPE_p_uint32_t.getCPtr(vAcc), SWIGTYPE_p_int32_t.getCPtr(hMSL));
  }

  public static boolean sqspLlaInit(SqspLla_t lla, SWIGTYPE_p_uint32_t iTOW, double lon, double lat, double height, double hMSL, double hAcc, double vAcc) {
    return sqspJNI.sqspLlaInit(SqspLla_t.getCPtr(lla), lla, SWIGTYPE_p_uint32_t.getCPtr(iTOW), lon, lat, height, hMSL, hAcc, vAcc);
  }

  public static boolean sqspLlaExpand(SqspLla_t lla, SqspLlaC_t llas) {
    return sqspJNI.sqspLlaExpand(SqspLla_t.getCPtr(lla), lla, SqspLlaC_t.getCPtr(llas), llas);
  }

  public static boolean sqspLlaCompact(SqspLlaC_t lla, SqspLla_t llas) {
    return sqspJNI.sqspLlaCompact(SqspLlaC_t.getCPtr(lla), lla, SqspLla_t.getCPtr(llas), llas);
  }

  public static String sqspSolutionTypeLabel(char index) {
    return sqspJNI.sqspSolutionTypeLabel(index);
  }

  public static SqspLbModeC_t sqspLbModeCCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspLbModeCCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspLbModeC_t(cPtr, false);
  }

  public static SqspLbModeC_t sqspLbModeCCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspLbModeC_t(sqspJNI.sqspLbModeCCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbModeC_t sqspLbModeCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLbModeC_t(sqspJNI.sqspLbModeCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbModeC_t sqspLbModeCConvertCopy(SqspLbMode_t lbms) {
    return new SqspLbModeC_t(sqspJNI.sqspLbModeCConvertCopy(SqspLbMode_t.getCPtr(lbms), lbms), true);
  }

  public static SqspLbModeC_t sqspLbModeCCreate(char fixedBaseEnable, char autoSurveyEnable, char connected, char correctionOutput, char correctionInput, char tripodCorrections, char validOrNotBusy, char broadcastEnable) {
    return new SqspLbModeC_t(sqspJNI.sqspLbModeCCreate(fixedBaseEnable, autoSurveyEnable, connected, correctionOutput, correctionInput, tripodCorrections, validOrNotBusy, broadcastEnable), true);
  }

  public static SqspLbConfigC_t sqspLbConfigCCast(byte[] JavaByteArray) {
    long cPtr = sqspJNI.sqspLbConfigCCast(JavaByteArray);
    return (cPtr == 0) ? null : new SqspLbConfigC_t(cPtr, false);
  }

  public static SqspLbConfigC_t sqspLbConfigCCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspLbConfigC_t(sqspJNI.sqspLbConfigCCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbConfigC_t sqspLbConfigCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLbConfigC_t(sqspJNI.sqspLbConfigCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbConfigC_t sqspLbConfigCConvertCopy(SqspLbConfig_t lbcs) {
    return new SqspLbConfigC_t(sqspJNI.sqspLbConfigCConvertCopy(SqspLbConfig_t.getCPtr(lbcs), lbcs), true);
  }

  public static SqspLbConfigC_t sqspLbConfigCCreate(SWIGTYPE_p_int32_t lon, SWIGTYPE_p_int32_t lat, SWIGTYPE_p_int32_t height, SWIGTYPE_p_uint32_t hAcc, SWIGTYPE_p_uint32_t vAcc, SWIGTYPE_p_int8_t lonHp, SWIGTYPE_p_int8_t latHp, SWIGTYPE_p_int8_t heightHp, SqspLbModeC_t mode, SWIGTYPE_p_uint32_t duration, SWIGTYPE_p_int32_t hMSL, SWIGTYPE_p_int8_t hMSLHp) {
    return new SqspLbConfigC_t(sqspJNI.sqspLbConfigCCreate(SWIGTYPE_p_int32_t.getCPtr(lon), SWIGTYPE_p_int32_t.getCPtr(lat), SWIGTYPE_p_int32_t.getCPtr(height), SWIGTYPE_p_uint32_t.getCPtr(hAcc), SWIGTYPE_p_uint32_t.getCPtr(vAcc), SWIGTYPE_p_int8_t.getCPtr(lonHp), SWIGTYPE_p_int8_t.getCPtr(latHp), SWIGTYPE_p_int8_t.getCPtr(heightHp), SqspLbModeC_t.getCPtr(mode), mode, SWIGTYPE_p_uint32_t.getCPtr(duration), SWIGTYPE_p_int32_t.getCPtr(hMSL), SWIGTYPE_p_int8_t.getCPtr(hMSLHp)), true);
  }

  public static SqspRspC_t sqspRspCCast(byte[] JavaByteArray) {
    long cPtr = sqspJNI.sqspRspCCast(JavaByteArray);
    return (cPtr == 0) ? null : new SqspRspC_t(cPtr, false);
  }

  public static SqspRspC_t sqspRspCCopy(byte[] JavaByteArray) {
    return new SqspRspC_t(sqspJNI.sqspRspCCopy(JavaByteArray), true);
  }

  public static SqspRspC_t sqspRspCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspRspC_t(sqspJNI.sqspRspCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRspC_t sqspRspCConvertCopy(SqspRsp_t rsps) {
    return new SqspRspC_t(sqspJNI.sqspRspCConvertCopy(SqspRsp_t.getCPtr(rsps), rsps), true);
  }

  public static SqspRspC_t sqspRspCCreate(SWIGTYPE_p_uint16_t mfgDataId, SWIGTYPE_p_uint8_t batteryLevel, SWIGTYPE_p_uint8_t systemPowerState, SWIGTYPE_p_uint16_t runTimeRemaining, SWIGTYPE_p_uint8_t satelliteCount, SWIGTYPE_p_uint8_t aidingBins, SWIGTYPE_p_uint8_t differential, SWIGTYPE_p_uint8_t gpsFixOk, SWIGTYPE_p_uint8_t ambiguity, SWIGTYPE_p_uint8_t fix, SWIGTYPE_p_uint8_t coprocOk, SWIGTYPE_p_uint8_t surveyFailed, SWIGTYPE_p_uint8_t surveyPositionValid, SWIGTYPE_p_uint8_t surveyInProgress, SWIGTYPE_p_uint8_t headingFlag, SWIGTYPE_p_uint8_t posValid, SWIGTYPE_p_uint8_t validTime, SqspLbModeC_t mode) {
    return new SqspRspC_t(sqspJNI.sqspRspCCreate(SWIGTYPE_p_uint16_t.getCPtr(mfgDataId), SWIGTYPE_p_uint8_t.getCPtr(batteryLevel), SWIGTYPE_p_uint8_t.getCPtr(systemPowerState), SWIGTYPE_p_uint16_t.getCPtr(runTimeRemaining), SWIGTYPE_p_uint8_t.getCPtr(satelliteCount), SWIGTYPE_p_uint8_t.getCPtr(aidingBins), SWIGTYPE_p_uint8_t.getCPtr(differential), SWIGTYPE_p_uint8_t.getCPtr(gpsFixOk), SWIGTYPE_p_uint8_t.getCPtr(ambiguity), SWIGTYPE_p_uint8_t.getCPtr(fix), SWIGTYPE_p_uint8_t.getCPtr(coprocOk), SWIGTYPE_p_uint8_t.getCPtr(surveyFailed), SWIGTYPE_p_uint8_t.getCPtr(surveyPositionValid), SWIGTYPE_p_uint8_t.getCPtr(surveyInProgress), SWIGTYPE_p_uint8_t.getCPtr(headingFlag), SWIGTYPE_p_uint8_t.getCPtr(posValid), SWIGTYPE_p_uint8_t.getCPtr(validTime), SqspLbModeC_t.getCPtr(mode), mode), true);
  }

  public static SqspStatusC_t sqspStatusCCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspStatusCCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspStatusC_t(cPtr, false);
  }

  public static SqspStatusC_t sqspStatusCCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspStatusC_t(sqspJNI.sqspStatusCCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspStatusC_t sqspStatusCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspStatusC_t(sqspJNI.sqspStatusCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspStatusC_t sqspStatusCConvertCopy(SqspStatus_t ss) {
    return new SqspStatusC_t(sqspJNI.sqspStatusCConvertCopy(SqspStatus_t.getCPtr(ss), ss), true);
  }

  public static SqspStatusC_t sqspStatusCCreate(int iTOW, short year, char month, char day, char hour, char min, char sec, char solType, char numSV, char battery, SqspRspC_t rsp) {
    return new SqspStatusC_t(sqspJNI.sqspStatusCCreate(iTOW, year, month, day, hour, min, sec, solType, numSV, battery, SqspRspC_t.getCPtr(rsp), rsp), true);
  }

  public static SqspRelPosC_t sqspRelPosCCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspRelPosCCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspRelPosC_t(cPtr, false);
  }

  public static SqspRelPosC_t sqspRelPosCCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspRelPosC_t(sqspJNI.sqspRelPosCCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRelPosC_t sqspRelPosCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspRelPosC_t(sqspJNI.sqspRelPosCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRelPosC_t sqspRelPosCConvertCopy(SqspRelPos_t rps) {
    return new SqspRelPosC_t(sqspJNI.sqspRelPosCConvertCopy(SqspRelPos_t.getCPtr(rps), rps), true);
  }

  public static SqspRelPosC_t sqspRelPosCCreate(SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_int32_t posN, SWIGTYPE_p_int32_t posE, SWIGTYPE_p_int32_t posD, SWIGTYPE_p_int8_t posHpN, SWIGTYPE_p_int8_t posHpE, SWIGTYPE_p_int8_t posHpD) {
    return new SqspRelPosC_t(sqspJNI.sqspRelPosCCreate(SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_int32_t.getCPtr(posN), SWIGTYPE_p_int32_t.getCPtr(posE), SWIGTYPE_p_int32_t.getCPtr(posD), SWIGTYPE_p_int8_t.getCPtr(posHpN), SWIGTYPE_p_int8_t.getCPtr(posHpE), SWIGTYPE_p_int8_t.getCPtr(posHpD)), true);
  }

  public static SqspLlaC_t sqspLlaCCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspLlaCCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspLlaC_t(cPtr, false);
  }

  public static SqspLlaC_t sqspLlaCCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspLlaC_t(sqspJNI.sqspLlaCCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLlaC_t sqspLlaCConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLlaC_t(sqspJNI.sqspLlaCConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLlaC_t sqspLlaCConvertCopy(SqspLla_t llas) {
    return new SqspLlaC_t(sqspJNI.sqspLlaCConvertCopy(SqspLla_t.getCPtr(llas), llas), true);
  }

  public static SqspLlaC_t sqspLlaCCreate(SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_int32_t lon, SWIGTYPE_p_int32_t lat, SWIGTYPE_p_int32_t height, SWIGTYPE_p_int8_t lonHp, SWIGTYPE_p_int8_t latHp, SWIGTYPE_p_int8_t heightHp, SWIGTYPE_p_int8_t hMSLHp, SWIGTYPE_p_uint32_t hAcc, SWIGTYPE_p_uint32_t vAcc, SWIGTYPE_p_int32_t hMSL) {
    return new SqspLlaC_t(sqspJNI.sqspLlaCCreate(SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_int32_t.getCPtr(lon), SWIGTYPE_p_int32_t.getCPtr(lat), SWIGTYPE_p_int32_t.getCPtr(height), SWIGTYPE_p_int8_t.getCPtr(lonHp), SWIGTYPE_p_int8_t.getCPtr(latHp), SWIGTYPE_p_int8_t.getCPtr(heightHp), SWIGTYPE_p_int8_t.getCPtr(hMSLHp), SWIGTYPE_p_uint32_t.getCPtr(hAcc), SWIGTYPE_p_uint32_t.getCPtr(vAcc), SWIGTYPE_p_int32_t.getCPtr(hMSL)), true);
  }

  public static SqspLbMode_t sqspLbModeCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspLbModeCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspLbMode_t(cPtr, false);
  }

  public static SqspLbMode_t sqspLbModeCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspLbMode_t(sqspJNI.sqspLbModeCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbMode_t sqspLbModeConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLbMode_t(sqspJNI.sqspLbModeConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbMode_t sqspLbModeConvertCopy(SqspLbModeC_t lbms) {
    return new SqspLbMode_t(sqspJNI.sqspLbModeConvertCopy(SqspLbModeC_t.getCPtr(lbms), lbms), true);
  }

  public static SqspLbMode_t sqspLbModeCreate(char fixedBaseEnable, char autoSurveyEnable, char connected, char correctionOutput, char correctionInput, char tripodCorrections, char validOrNotBusy, char broadcastEnable) {
    return new SqspLbMode_t(sqspJNI.sqspLbModeCreate(fixedBaseEnable, autoSurveyEnable, connected, correctionOutput, correctionInput, tripodCorrections, validOrNotBusy, broadcastEnable), true);
  }

  public static SqspLbConfig_t sqspLbConfigCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspLbConfigCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspLbConfig_t(cPtr, false);
  }

  public static SqspLbConfig_t sqspLbConfigCopy(byte[] JavaByteArray) {
    return new SqspLbConfig_t(sqspJNI.sqspLbConfigCopy(JavaByteArray), true);
  }

  public static SqspLbConfig_t sqspLbConfigConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLbConfig_t(sqspJNI.sqspLbConfigConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLbConfig_t sqspLbConfigConvertCopy(SqspLbConfigC_t lbcs) {
    return new SqspLbConfig_t(sqspJNI.sqspLbConfigConvertCopy(SqspLbConfigC_t.getCPtr(lbcs), lbcs), true);
  }

  public static SqspLbConfig_t sqspLbConfigCreate(double lon, double lat, double height, double hMSL, double hAcc, double vAcc, int duration, SqspLbMode_t mode) {
    return new SqspLbConfig_t(sqspJNI.sqspLbConfigCreate(lon, lat, height, hMSL, hAcc, vAcc, duration, SqspLbMode_t.getCPtr(mode), mode), true);
  }

  public static SqspRsp_t sqspRspCast(byte[] JavaByteArray) {
    long cPtr = sqspJNI.sqspRspCast(JavaByteArray);
    return (cPtr == 0) ? null : new SqspRsp_t(cPtr, false);
  }

  public static SqspRsp_t sqspRspCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspRsp_t(sqspJNI.sqspRspCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRsp_t sqspRspConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspRsp_t(sqspJNI.sqspRspConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRsp_t sqspRspConvertCopy(SqspRspC_t rsps) {
    return new SqspRsp_t(sqspJNI.sqspRspConvertCopy(SqspRspC_t.getCPtr(rsps), rsps), true);
  }

  public static SqspRsp_t sqspRspCreate(SWIGTYPE_p_uint16_t mfgDataId, SWIGTYPE_p_uint8_t batteryLevel, SWIGTYPE_p_uint8_t systemPowerState, SWIGTYPE_p_uint16_t runTimeRemaining, SWIGTYPE_p_uint8_t satelliteCount, SWIGTYPE_p_uint8_t aidingBins, SWIGTYPE_p_uint8_t differential, SWIGTYPE_p_uint8_t gpsFixOk, SWIGTYPE_p_uint8_t ambiguity, SWIGTYPE_p_uint8_t fix, SWIGTYPE_p_uint8_t coprocOk, SWIGTYPE_p_uint8_t surveyFailed, SWIGTYPE_p_uint8_t surveyPositionValid, SWIGTYPE_p_uint8_t surveyInProgress, SWIGTYPE_p_uint8_t headingFlag, SWIGTYPE_p_uint8_t posValid, SWIGTYPE_p_uint8_t validTime, SqspLbMode_t mode) {
    return new SqspRsp_t(sqspJNI.sqspRspCreate(SWIGTYPE_p_uint16_t.getCPtr(mfgDataId), SWIGTYPE_p_uint8_t.getCPtr(batteryLevel), SWIGTYPE_p_uint8_t.getCPtr(systemPowerState), SWIGTYPE_p_uint16_t.getCPtr(runTimeRemaining), SWIGTYPE_p_uint8_t.getCPtr(satelliteCount), SWIGTYPE_p_uint8_t.getCPtr(aidingBins), SWIGTYPE_p_uint8_t.getCPtr(differential), SWIGTYPE_p_uint8_t.getCPtr(gpsFixOk), SWIGTYPE_p_uint8_t.getCPtr(ambiguity), SWIGTYPE_p_uint8_t.getCPtr(fix), SWIGTYPE_p_uint8_t.getCPtr(coprocOk), SWIGTYPE_p_uint8_t.getCPtr(surveyFailed), SWIGTYPE_p_uint8_t.getCPtr(surveyPositionValid), SWIGTYPE_p_uint8_t.getCPtr(surveyInProgress), SWIGTYPE_p_uint8_t.getCPtr(headingFlag), SWIGTYPE_p_uint8_t.getCPtr(posValid), SWIGTYPE_p_uint8_t.getCPtr(validTime), SqspLbMode_t.getCPtr(mode), mode), true);
  }

  public static SqspStatus_t sqspStatusCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspStatusCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspStatus_t(cPtr, false);
  }

  public static SqspStatus_t sqspStatusCopy(byte[] JavaByteArray) {
    return new SqspStatus_t(sqspJNI.sqspStatusCopy(JavaByteArray), true);
  }

  public static SqspStatus_t sqspStatusConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspStatus_t(sqspJNI.sqspStatusConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspStatus_t sqspStatusConvertCopy(SqspStatusC_t ss) {
    return new SqspStatus_t(sqspJNI.sqspStatusConvertCopy(SqspStatusC_t.getCPtr(ss), ss), true);
  }

  public static SqspStatus_t sqspStatusCreate(SWIGTYPE_p_uint32_t iTOW, SWIGTYPE_p_uint32_t time, SWIGTYPE_p_uint8_t solType, SWIGTYPE_p_uint8_t numSV, SWIGTYPE_p_uint8_t battery, SqspRsp_t rsp) {
    return new SqspStatus_t(sqspJNI.sqspStatusCreate(SWIGTYPE_p_uint32_t.getCPtr(iTOW), SWIGTYPE_p_uint32_t.getCPtr(time), SWIGTYPE_p_uint8_t.getCPtr(solType), SWIGTYPE_p_uint8_t.getCPtr(numSV), SWIGTYPE_p_uint8_t.getCPtr(battery), SqspRsp_t.getCPtr(rsp), rsp), true);
  }

  public static SqspRelPos_t sqspRelPosCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspRelPosCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspRelPos_t(cPtr, false);
  }

  public static SqspRelPos_t sqspRelPosCopy(SWIGTYPE_p_uint8_t p) {
    return new SqspRelPos_t(sqspJNI.sqspRelPosCopy(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRelPos_t sqspRelPosConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspRelPos_t(sqspJNI.sqspRelPosConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspRelPos_t sqspRelPosConvertCopy(SqspRelPosC_t rps) {
    return new SqspRelPos_t(sqspJNI.sqspRelPosConvertCopy(SqspRelPosC_t.getCPtr(rps), rps), true);
  }

  public static SqspRelPos_t sqspRelPosCreate(SWIGTYPE_p_uint32_t iTOW, double posN, double posE, double posD) {
    return new SqspRelPos_t(sqspJNI.sqspRelPosCreate(SWIGTYPE_p_uint32_t.getCPtr(iTOW), posN, posE, posD), true);
  }

  public static SqspLla_t sqspLlaCast(SWIGTYPE_p_uint8_t p) {
    long cPtr = sqspJNI.sqspLlaCast(SWIGTYPE_p_uint8_t.getCPtr(p));
    return (cPtr == 0) ? null : new SqspLla_t(cPtr, false);
  }

  public static SqspLla_t sqspLlaCopy(byte[] JavaByteArray) {
    return new SqspLla_t(sqspJNI.sqspLlaCopy(JavaByteArray), true);
  }

  public static SqspLla_t sqspLlaConvertCast(SWIGTYPE_p_uint8_t p) {
    return new SqspLla_t(sqspJNI.sqspLlaConvertCast(SWIGTYPE_p_uint8_t.getCPtr(p)), true);
  }

  public static SqspLla_t sqspLlaConvertCopy(SqspLlaC_t llas) {
    return new SqspLla_t(sqspJNI.sqspLlaConvertCopy(SqspLlaC_t.getCPtr(llas), llas), true);
  }

  public static SqspLla_t sqspLlaCreate(int iTOW, double lon, double lat, double height, double hMSL, double hAcc, double vAcc) {
    return new SqspLla_t(sqspJNI.sqspLlaCreate(iTOW, lon, lat, height, hMSL, hAcc, vAcc), true);
  }

  public static SqspSolTypeLabel_t sqspSolutionTypeLabelCopy(char index) {
    return new SqspSolTypeLabel_t(sqspJNI.sqspSolutionTypeLabelCopy(index), true);
  }

  public static int SqspSqspLbModeC_tByteArray(byte[] JavaByteArray, int Length, SqspLbModeC_t Mode) {
    return sqspJNI.SqspSqspLbModeC_tByteArray(JavaByteArray, Length, SqspLbModeC_t.getCPtr(Mode), Mode);
  }

  public static int SqspLbMode_tByteArray(byte[] JavaByteArray, int Length, SqspLbMode_t Mode) {
    return sqspJNI.SqspLbMode_tByteArray(JavaByteArray, Length, SqspLbMode_t.getCPtr(Mode), Mode);
  }

  public static int SqspRspC_tByteArray(byte[] JavaByteArray, int Length, SqspRspC_t Response) {
    return sqspJNI.SqspRspC_tByteArray(JavaByteArray, Length, SqspRspC_t.getCPtr(Response), Response);
  }

  public static int SqspRsp_tByteArray(byte[] JavaByteArray, int Length, SqspRsp_t Response) {
    return sqspJNI.SqspRsp_tByteArray(JavaByteArray, Length, SqspRsp_t.getCPtr(Response), Response);
  }

  public static int SqspStatus_tByteArray(byte[] JavaByteArray, int Length, SqspStatus_t Status) {
    return sqspJNI.SqspStatus_tByteArray(JavaByteArray, Length, SqspStatus_t.getCPtr(Status), Status);
  }

  public static int SqspStatusC_tByteArray(byte[] JavaByteArray, int length, SqspStatusC_t Status) {
    return sqspJNI.SqspStatusC_tByteArray(JavaByteArray, length, SqspStatusC_t.getCPtr(Status), Status);
  }

  public static int SqspLlaC_tByteArray(byte[] JavaByteArray, int Length, SqspLlaC_t LLA) {
    return sqspJNI.SqspLlaC_tByteArray(JavaByteArray, Length, SqspLlaC_t.getCPtr(LLA), LLA);
  }

  public static int SqspLla_tByteArray(byte[] JavaByteArray, int Length, SqspLla_t LLA) {
    return sqspJNI.SqspLla_tByteArray(JavaByteArray, Length, SqspLla_t.getCPtr(LLA), LLA);
  }

  public static int SqspLbConfig_tByteArray(byte[] JavaByteArray, int Length, SqspLbConfig_t Config) {
    return sqspJNI.SqspLbConfig_tByteArray(JavaByteArray, Length, SqspLbConfig_t.getCPtr(Config), Config);
  }

  public static int SqspLbConfigC_tByteArray(byte[] JavaByteArray, int Length, SqspLbConfigC_t Config) {
    return sqspJNI.SqspLbConfigC_tByteArray(JavaByteArray, Length, SqspLbConfigC_t.getCPtr(Config), Config);
  }

  public static int SqspLbModeC_tSize() {
    return sqspJNI.SqspLbModeC_tSize();
  }

  public static int SqspLbMode_tSize() {
    return sqspJNI.SqspLbMode_tSize();
  }

  public static int SqspRspC_tSize() {
    return sqspJNI.SqspRspC_tSize();
  }

  public static int SqspRsp_tSize() {
    return sqspJNI.SqspRsp_tSize();
  }

  public static int SqspStatus_tSize() {
    return sqspJNI.SqspStatus_tSize();
  }

  public static int SqspStatusC_tSize() {
    return sqspJNI.SqspStatusC_tSize();
  }

  public static int SqspLlaC_tSize() {
    return sqspJNI.SqspLlaC_tSize();
  }

  public static int SqspLla_tSize() {
    return sqspJNI.SqspLla_tSize();
  }

  public static int SqspLbConfig_tSize() {
    return sqspJNI.SqspLbConfig_tSize();
  }

  public static int SqspLbConfigC_tSize() {
    return sqspJNI.SqspLbConfigC_tSize();
  }

  public static SqspStatus_t sqspStatusCopyCast(byte[] JavaByteArray) {
    return new SqspStatus_t(sqspJNI.sqspStatusCopyCast(JavaByteArray), true);
  }

}
