/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspStatusC_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspStatusC_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspStatusC_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspStatusC_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspStatusC_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setITOW(SWIGTYPE_p_uint32_t value) {
    sqspJNI.SqspStatusC_t_iTOW_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getITOW() {
    return new SWIGTYPE_p_uint32_t(sqspJNI.SqspStatusC_t_iTOW_get(swigCPtr, this), true);
  }

  public void setYear(SWIGTYPE_p_uint16_t value) {
    sqspJNI.SqspStatusC_t_year_set(swigCPtr, this, SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint16_t getYear() {
    return new SWIGTYPE_p_uint16_t(sqspJNI.SqspStatusC_t_year_get(swigCPtr, this), true);
  }

  public void setMonth(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_month_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getMonth() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_month_get(swigCPtr, this), true);
  }

  public void setDay(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_day_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getDay() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_day_get(swigCPtr, this), true);
  }

  public void setHour(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_hour_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getHour() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_hour_get(swigCPtr, this), true);
  }

  public void setMin(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_min_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getMin() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_min_get(swigCPtr, this), true);
  }

  public void setSec(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_sec_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getSec() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_sec_get(swigCPtr, this), true);
  }

  public void setSolType(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_solType_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getSolType() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_solType_get(swigCPtr, this), true);
  }

  public void setNumSV(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_numSV_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getNumSV() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_numSV_get(swigCPtr, this), true);
  }

  public void setBattery(SWIGTYPE_p_uint8_t value) {
    sqspJNI.SqspStatusC_t_battery_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getBattery() {
    return new SWIGTYPE_p_uint8_t(sqspJNI.SqspStatusC_t_battery_get(swigCPtr, this), true);
  }

  public void setRsp(SqspRspC_t value) {
    sqspJNI.SqspStatusC_t_rsp_set(swigCPtr, this, SqspRspC_t.getCPtr(value), value);
  }

  public SqspRspC_t getRsp() {
    long cPtr = sqspJNI.SqspStatusC_t_rsp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SqspRspC_t(cPtr, false);
  }

  public SqspStatusC_t() {
    this(sqspJNI.new_SqspStatusC_t(), true);
  }

}
