/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspLbConfig_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspLbConfig_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspLbConfig_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspLbConfig_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspLbConfig_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLon(double value) {
    sqspJNI.SqspLbConfig_t_lon_set(swigCPtr, this, value);
  }

  public double getLon() {
    return sqspJNI.SqspLbConfig_t_lon_get(swigCPtr, this);
  }

  public void setLat(double value) {
    sqspJNI.SqspLbConfig_t_lat_set(swigCPtr, this, value);
  }

  public double getLat() {
    return sqspJNI.SqspLbConfig_t_lat_get(swigCPtr, this);
  }

  public void setHeight(double value) {
    sqspJNI.SqspLbConfig_t_height_set(swigCPtr, this, value);
  }

  public double getHeight() {
    return sqspJNI.SqspLbConfig_t_height_get(swigCPtr, this);
  }

  public void setHMSL(double value) {
    sqspJNI.SqspLbConfig_t_hMSL_set(swigCPtr, this, value);
  }

  public double getHMSL() {
    return sqspJNI.SqspLbConfig_t_hMSL_get(swigCPtr, this);
  }

  public void setHAcc(double value) {
    sqspJNI.SqspLbConfig_t_hAcc_set(swigCPtr, this, value);
  }

  public double getHAcc() {
    return sqspJNI.SqspLbConfig_t_hAcc_get(swigCPtr, this);
  }

  public void setVAcc(double value) {
    sqspJNI.SqspLbConfig_t_vAcc_set(swigCPtr, this, value);
  }

  public double getVAcc() {
    return sqspJNI.SqspLbConfig_t_vAcc_get(swigCPtr, this);
  }

  public void setDuration(int value) {
    sqspJNI.SqspLbConfig_t_duration_set(swigCPtr, this, value);
  }

  public int getDuration() {
    return sqspJNI.SqspLbConfig_t_duration_get(swigCPtr, this);
  }

  public void setMode(SqspLbMode_t value) {
    sqspJNI.SqspLbConfig_t_mode_set(swigCPtr, this, SqspLbMode_t.getCPtr(value), value);
  }

  public SqspLbMode_t getMode() {
    long cPtr = sqspJNI.SqspLbConfig_t_mode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SqspLbMode_t(cPtr, false);
  }

  public void setReserved(String value) {
    sqspJNI.SqspLbConfig_t_reserved_set(swigCPtr, this, value);
  }

  public String getReserved() {
    return sqspJNI.SqspLbConfig_t_reserved_get(swigCPtr, this);
  }

  public SqspLbConfig_t() {
    this(sqspJNI.new_SqspLbConfig_t(), true);
  }

}
