/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspLbConfigC_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspLbConfigC_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspLbConfigC_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspLbConfigC_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspLbConfigC_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLon(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspLbConfigC_t_lon_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getLon() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspLbConfigC_t_lon_get(swigCPtr, this), true);
  }

  public void setLat(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspLbConfigC_t_lat_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getLat() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspLbConfigC_t_lat_get(swigCPtr, this), true);
  }

  public void setHeight(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspLbConfigC_t_height_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getHeight() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspLbConfigC_t_height_get(swigCPtr, this), true);
  }

  public void setHAcc(SWIGTYPE_p_uint32_t value) {
    sqspJNI.SqspLbConfigC_t_hAcc_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getHAcc() {
    return new SWIGTYPE_p_uint32_t(sqspJNI.SqspLbConfigC_t_hAcc_get(swigCPtr, this), true);
  }

  public void setVAcc(SWIGTYPE_p_uint32_t value) {
    sqspJNI.SqspLbConfigC_t_vAcc_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getVAcc() {
    return new SWIGTYPE_p_uint32_t(sqspJNI.SqspLbConfigC_t_vAcc_get(swigCPtr, this), true);
  }

  public void setLonHp(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspLbConfigC_t_lonHp_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getLonHp() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspLbConfigC_t_lonHp_get(swigCPtr, this), true);
  }

  public void setLatHp(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspLbConfigC_t_latHp_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getLatHp() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspLbConfigC_t_latHp_get(swigCPtr, this), true);
  }

  public void setHeightHp(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspLbConfigC_t_heightHp_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getHeightHp() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspLbConfigC_t_heightHp_get(swigCPtr, this), true);
  }

  public void setMode(SqspLbModeC_t value) {
    sqspJNI.SqspLbConfigC_t_mode_set(swigCPtr, this, SqspLbModeC_t.getCPtr(value), value);
  }

  public SqspLbModeC_t getMode() {
    long cPtr = sqspJNI.SqspLbConfigC_t_mode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SqspLbModeC_t(cPtr, false);
  }

  public void setDuration(SWIGTYPE_p_uint32_t value) {
    sqspJNI.SqspLbConfigC_t_duration_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getDuration() {
    return new SWIGTYPE_p_uint32_t(sqspJNI.SqspLbConfigC_t_duration_get(swigCPtr, this), true);
  }

  public void setHMSL(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspLbConfigC_t_hMSL_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getHMSL() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspLbConfigC_t_hMSL_get(swigCPtr, this), true);
  }

  public void setHMSLHp(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspLbConfigC_t_hMSLHp_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getHMSLHp() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspLbConfigC_t_hMSLHp_get(swigCPtr, this), true);
  }

  public void setReserved(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspLbConfigC_t_reserved_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getReserved() {
    long cPtr = sqspJNI.SqspLbConfigC_t_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int8_t(cPtr, false);
  }

  public SqspLbConfigC_t() {
    this(sqspJNI.new_SqspLbConfigC_t(), true);
  }

}
