/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspLbMode_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspLbMode_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspLbMode_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspLbMode_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspLbMode_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFixedBaseEnable(char value) {
    sqspJNI.SqspLbMode_t_fixedBaseEnable_set(swigCPtr, this, value);
  }

  public char getFixedBaseEnable() {
    return sqspJNI.SqspLbMode_t_fixedBaseEnable_get(swigCPtr, this);
  }

  public void setAutoSurveyEnable(char value) {
    sqspJNI.SqspLbMode_t_autoSurveyEnable_set(swigCPtr, this, value);
  }

  public char getAutoSurveyEnable() {
    return sqspJNI.SqspLbMode_t_autoSurveyEnable_get(swigCPtr, this);
  }

  public void setConnected(char value) {
    sqspJNI.SqspLbMode_t_connected_set(swigCPtr, this, value);
  }

  public char getConnected() {
    return sqspJNI.SqspLbMode_t_connected_get(swigCPtr, this);
  }

  public void setCorrectionOutput(char value) {
    sqspJNI.SqspLbMode_t_correctionOutput_set(swigCPtr, this, value);
  }

  public char getCorrectionOutput() {
    return sqspJNI.SqspLbMode_t_correctionOutput_get(swigCPtr, this);
  }

  public void setCorrectionInput(char value) {
    sqspJNI.SqspLbMode_t_correctionInput_set(swigCPtr, this, value);
  }

  public char getCorrectionInput() {
    return sqspJNI.SqspLbMode_t_correctionInput_get(swigCPtr, this);
  }

  public void setTripodCorrections(char value) {
    sqspJNI.SqspLbMode_t_tripodCorrections_set(swigCPtr, this, value);
  }

  public char getTripodCorrections() {
    return sqspJNI.SqspLbMode_t_tripodCorrections_get(swigCPtr, this);
  }

  public void setValidOrNotBusy(char value) {
    sqspJNI.SqspLbMode_t_validOrNotBusy_set(swigCPtr, this, value);
  }

  public char getValidOrNotBusy() {
    return sqspJNI.SqspLbMode_t_validOrNotBusy_get(swigCPtr, this);
  }

  public void setBroadcastEnable(char value) {
    sqspJNI.SqspLbMode_t_broadcastEnable_set(swigCPtr, this, value);
  }

  public char getBroadcastEnable() {
    return sqspJNI.SqspLbMode_t_broadcastEnable_get(swigCPtr, this);
  }

  public SqspLbMode_t() {
    this(sqspJNI.new_SqspLbMode_t(), true);
  }

}
