/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspRelPosC_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspRelPosC_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspRelPosC_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspRelPosC_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspRelPosC_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setITOW(SWIGTYPE_p_uint32_t value) {
    sqspJNI.SqspRelPosC_t_iTOW_set(swigCPtr, this, SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint32_t getITOW() {
    return new SWIGTYPE_p_uint32_t(sqspJNI.SqspRelPosC_t_iTOW_get(swigCPtr, this), true);
  }

  public void setPosN(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspRelPosC_t_posN_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getPosN() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspRelPosC_t_posN_get(swigCPtr, this), true);
  }

  public void setPosE(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspRelPosC_t_posE_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getPosE() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspRelPosC_t_posE_get(swigCPtr, this), true);
  }

  public void setPosD(SWIGTYPE_p_int32_t value) {
    sqspJNI.SqspRelPosC_t_posD_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t getPosD() {
    return new SWIGTYPE_p_int32_t(sqspJNI.SqspRelPosC_t_posD_get(swigCPtr, this), true);
  }

  public void setPosHpN(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspRelPosC_t_posHpN_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getPosHpN() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspRelPosC_t_posHpN_get(swigCPtr, this), true);
  }

  public void setPosHpE(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspRelPosC_t_posHpE_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getPosHpE() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspRelPosC_t_posHpE_get(swigCPtr, this), true);
  }

  public void setPosHpD(SWIGTYPE_p_int8_t value) {
    sqspJNI.SqspRelPosC_t_posHpD_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getPosHpD() {
    return new SWIGTYPE_p_int8_t(sqspJNI.SqspRelPosC_t_posHpD_get(swigCPtr, this), true);
  }

  public SqspRelPosC_t() {
    this(sqspJNI.new_SqspRelPosC_t(), true);
  }

}
