/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspSolTypeLabel_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspSolTypeLabel_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspSolTypeLabel_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspSolTypeLabel_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspSolTypeLabel_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setString(String value) {
    sqspJNI.SqspSolTypeLabel_t_string_set(swigCPtr, this, value);
  }

  public String getString() {
    return sqspJNI.SqspSolTypeLabel_t_string_get(swigCPtr, this);
  }

  public SqspSolTypeLabel_t() {
    this(sqspJNI.new_SqspSolTypeLabel_t(), true);
  }

}
