/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public final class SqspHostMcuCommand_t {
  public final static SqspHostMcuCommand_t SQSP_HOST_COMMAND_NONE = new SqspHostMcuCommand_t("SQSP_HOST_COMMAND_NONE", sqspJNI.SQSP_HOST_COMMAND_NONE_get());
  public final static SqspHostMcuCommand_t SQSP_HOST_COMMAND_START_TRIPOD_AIDING = new SqspHostMcuCommand_t("SQSP_HOST_COMMAND_START_TRIPOD_AIDING", sqspJNI.SQSP_HOST_COMMAND_START_TRIPOD_AIDING_get());
  public final static SqspHostMcuCommand_t SQSP_HOST_COMMAND_STOP_TRIPOD_AIDING = new SqspHostMcuCommand_t("SQSP_HOST_COMMAND_STOP_TRIPOD_AIDING", sqspJNI.SQSP_HOST_COMMAND_STOP_TRIPOD_AIDING_get());
  public final static SqspHostMcuCommand_t SQSP_HOST_COMMAND_START_TRIPOD_AIDING_DELAYED = new SqspHostMcuCommand_t("SQSP_HOST_COMMAND_START_TRIPOD_AIDING_DELAYED", sqspJNI.SQSP_HOST_COMMAND_START_TRIPOD_AIDING_DELAYED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SqspHostMcuCommand_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SqspHostMcuCommand_t.class + " with value " + swigValue);
  }

  private SqspHostMcuCommand_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SqspHostMcuCommand_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SqspHostMcuCommand_t(String swigName, SqspHostMcuCommand_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SqspHostMcuCommand_t[] swigValues = { SQSP_HOST_COMMAND_NONE, SQSP_HOST_COMMAND_START_TRIPOD_AIDING, SQSP_HOST_COMMAND_STOP_TRIPOD_AIDING, SQSP_HOST_COMMAND_START_TRIPOD_AIDING_DELAYED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

