/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqsp;

public class SqspStatus_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqspStatus_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqspStatus_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqspStatus_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqspJNI.delete_SqspStatus_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setITOW(int value) {
    sqspJNI.SqspStatus_t_iTOW_set(swigCPtr, this, value);
  }

  public int getITOW() {
    return sqspJNI.SqspStatus_t_iTOW_get(swigCPtr, this);
  }

  public void setTime(int value) {
    sqspJNI.SqspStatus_t_time_set(swigCPtr, this, value);
  }

  public int getTime() {
    return sqspJNI.SqspStatus_t_time_get(swigCPtr, this);
  }

  public void setSolType(char value) {
    sqspJNI.SqspStatus_t_solType_set(swigCPtr, this, value);
  }

  public char getSolType() {
    return sqspJNI.SqspStatus_t_solType_get(swigCPtr, this);
  }

  public void setNumSV(char value) {
    sqspJNI.SqspStatus_t_numSV_set(swigCPtr, this, value);
  }

  public char getNumSV() {
    return sqspJNI.SqspStatus_t_numSV_get(swigCPtr, this);
  }

  public void setBattery(char value) {
    sqspJNI.SqspStatus_t_battery_set(swigCPtr, this, value);
  }

  public char getBattery() {
    return sqspJNI.SqspStatus_t_battery_get(swigCPtr, this);
  }

  public void setReserved(char value) {
    sqspJNI.SqspStatus_t_reserved_set(swigCPtr, this, value);
  }

  public char getReserved() {
    return sqspJNI.SqspStatus_t_reserved_get(swigCPtr, this);
  }

  public void setRsp(SqspRsp_t value) {
    sqspJNI.SqspStatus_t_rsp_set(swigCPtr, this, SqspRsp_t.getCPtr(value), value);
  }

  public SqspRsp_t getRsp() {
    long cPtr = sqspJNI.SqspStatus_t_rsp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SqspRsp_t(cPtr, false);
  }

  public void setReserved2(char value) {
    sqspJNI.SqspStatus_t_reserved2_set(swigCPtr, this, value);
  }

  public char getReserved2() {
    return sqspJNI.SqspStatus_t_reserved2_get(swigCPtr, this);
  }

  public SqspStatus_t() {
    this(sqspJNI.new_SqspStatus_t(), true);
  }

}
