/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)



//#include "stdint.h"

#include "os_target.h"
//#include "../sqsp/sqspTypes.h"    //DO NOT enable: We'll pull this library's coding in using import statements
//#include "../sqsp/sqspTypeWrap.h" //DO NOT enable: We'll pull this library's coding in using import statements
#include "sqtpFrame.h"
#include "sqtpStatus.h"
#include "sqtpSubframeIDs.h"


//// Deprecated? Functional?
////SqtpStatus_t sqtpFrameWriterFinalizeData(SqtpFrameWriter_t *FW, uint8_t *JavaByteArray, int Length)
//SqtpStatus_t sqtpFrameWriterFinalizeData(SqtpFrameWriter_t *FW, uint8_t *buffer, int length)
//{
//    if( FW == NULL)  return(-11);
//    if( buffer == NULL)  return(-10);
//    if( length <= 0)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
//    if( length < FW->index)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
//
//    SqtpStatus_t status = sqtpFrameWriterFinalize(FW);
//    if(status < SQTP_STATUS_SUCCESS) return(status);
//
//    for(int i=0; i < FW->index; i++)
//        buffer[i] = FW->frame[i];
//
//    return(SQTP_STATUS_SUCCESS);
//}

//// Deprecated? Functional?
////SqtpStatus_t GetSubFramePayloadByteArray(SqtpSubframe_t *SubFrame, uint8_t *JavaByteArray, int Length)
////SqtpStatus_t GetSubFramePayloadByteArray(SqtpSubframe_t *SubFrame, uint8_t *buffer, int length)
//SqtpStatus_t GetSubFramePayloadByteArray(SqtpSubframe_t SubFrame, uint8_t *buffer, int length)
//{
//    if( &SubFrame == NULL)  return(-11);
//    if( buffer == NULL)  return(-10);
//    if( length <= 0)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
//    if( SubFrame.length == 0)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
//    if( length != SubFrame.length)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
//
//    for(int i=0; i < SubFrame.length; i++)
//        buffer[i] = SubFrame.payload[i];
//
//    return(SQTP_STATUS_SUCCESS);
//}


//SqtpStatus_t GetSubFrameByteArray(SqtpFrameReader_t *Reader, uint8_t *JavaByteArray, int Length)
SqtpStatus_t GetSubFrameByteArray(SqtpFrameReader_t *Reader, uint8_t *buffer, int length)
{
    if( Reader == NULL)  return(-11);
    if( buffer == NULL)  return(-10);
    if( length <= 0)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
    if( Reader->subframe.length == 0)  return(SQTP_STATUS_FRAME_BAD_LENGTH);
    if( length != Reader->subframe.length)  return(SQTP_STATUS_FRAME_BAD_LENGTH);

    for(int i=0; i < Reader->subframe.length; i++)
        buffer[i] = Reader->subframe.payload[i];

    return(SQTP_STATUS_SUCCESS);
}



#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1payload_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->payload = (uint8_t const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1payload_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->payload);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  SqtpSubframeId_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  arg2 = (SqtpSubframeId_t)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  SqtpSubframeId_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  result = (SqtpSubframeId_t) ((arg1)->id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpSubframe_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  result =  ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_new_1SqtpSubframe_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct SqtpSubframe_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct SqtpSubframe_s *)calloc(1, sizeof(struct SqtpSubframe_s));
  *(struct SqtpSubframe_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_delete_1SqtpSubframe_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct SqtpSubframe_s *arg1 = (struct SqtpSubframe_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct SqtpSubframe_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1frame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->frame = (uint8_t const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1frame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->frame);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  result =  ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1index_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->index = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1index_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  result =  ((arg1)->index);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  SqtpStatus_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  arg2 = (SqtpStatus_t)jarg2; 
  if (arg1) (arg1)->status = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  result = (SqtpStatus_t) ((arg1)->status);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1subframe_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  SqtpSubframe_t *arg2 = (SqtpSubframe_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  arg2 = *(SqtpSubframe_t **)&jarg2; 
  if (arg1) (arg1)->subframe = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameReader_1t_1subframe_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  SqtpSubframe_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  result = (SqtpSubframe_t *)& ((arg1)->subframe);
  *(SqtpSubframe_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_new_1SqtpFrameReader_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct SqtpFrameReader_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct SqtpFrameReader_s *)calloc(1, sizeof(struct SqtpFrameReader_s));
  *(struct SqtpFrameReader_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_delete_1SqtpFrameReader_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct SqtpFrameReader_s *arg1 = (struct SqtpFrameReader_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct SqtpFrameReader_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1frame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->frame = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1frame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->frame);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  result =  ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1index_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->index = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1index_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  result =  ((arg1)->index);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  SqtpStatus_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  arg2 = (SqtpStatus_t)jarg2; 
  if (arg1) (arg1)->status = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpFrameWriter_1t_1status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  result = (SqtpStatus_t) ((arg1)->status);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_new_1SqtpFrameWriter_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct SqtpFrameWriter_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct SqtpFrameWriter_s *)calloc(1, sizeof(struct SqtpFrameWriter_s));
  *(struct SqtpFrameWriter_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_delete_1SqtpFrameWriter_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct SqtpFrameWriter_s *arg1 = (struct SqtpFrameWriter_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct SqtpFrameWriter_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameGetLength(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint8_t **)&jarg1; 
  result = sqtpFrameGetLength((uint8_t const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderInit(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3) {
  jint jresult = 0 ;
  SqtpFrameReader_t *arg1 = (SqtpFrameReader_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameReader_t **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (size_t)jarg3; 
  result = (SqtpStatus_t)sqtpFrameReaderInit(arg1,(uint8_t const *)arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderReset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqtpFrameReader_t *arg1 = (SqtpFrameReader_t *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameReader_t **)&jarg1; 
  result = (SqtpStatus_t)sqtpFrameReaderReset(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderNext(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqtpFrameReader_t *arg1 = (SqtpFrameReader_t *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameReader_t **)&jarg1; 
  result = (SqtpStatus_t)sqtpFrameReaderNext(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterInit(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3) {
  jint jresult = 0 ;
  SqtpFrameWriter_t *arg1 = (SqtpFrameWriter_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameWriter_t **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (size_t)jarg3; 
  result = (SqtpStatus_t)sqtpFrameWriterInit(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterReset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqtpFrameWriter_t *arg1 = (SqtpFrameWriter_t *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameWriter_t **)&jarg1; 
  result = (SqtpStatus_t)sqtpFrameWriterReset(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterWriteDirect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jbyteArray jarg3, jlong jarg4) {
  jint jresult = 0 ;
  SqtpFrameWriter_t *arg1 = (SqtpFrameWriter_t *) 0 ;
  SqtpSubframeId_t arg2 ;
  uint8_t *arg3 = (uint8_t *) 0 ;
  size_t arg4 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameWriter_t **)&jarg1; 
  arg2 = (SqtpSubframeId_t)jarg2; 
  {
    arg3 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg3, 0); 
  }
  arg4 = (size_t)jarg4; 
  result = (SqtpStatus_t)sqtpFrameWriterWriteDirect(arg1,arg2,(uint8_t const *)arg3,arg4);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg3, (jbyte *) arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterWriteSubframe(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  SqtpFrameWriter_t *arg1 = (SqtpFrameWriter_t *) 0 ;
  SqtpSubframe_t *arg2 = (SqtpSubframe_t *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SqtpFrameWriter_t **)&jarg1; 
  arg2 = *(SqtpSubframe_t **)&jarg2; 
  result = (SqtpStatus_t)sqtpFrameWriterWriteSubframe(arg1,(struct SqtpSubframe_s const *)arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterFinalize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqtpFrameWriter_t *arg1 = (SqtpFrameWriter_t *) 0 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameWriter_t **)&jarg1; 
  result = (SqtpStatus_t)sqtpFrameWriterFinalize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderInitStruct(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  size_t arg2 ;
  SqtpFrameReader_t result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (size_t)jarg2; 
  result = sqtpFrameReaderInitStruct((uint8_t const *)arg1,arg2);
  {
    SqtpFrameReader_t * resultptr = (SqtpFrameReader_t *) malloc(sizeof(SqtpFrameReader_t));
    memmove(resultptr, &result, sizeof(SqtpFrameReader_t));
    *(SqtpFrameReader_t **)&jresult = resultptr;
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderResetStruct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  SqtpFrameReader_t arg1 ;
  SqtpFrameReader_t *argp1 ;
  SqtpFrameReader_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(SqtpFrameReader_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpFrameReader_t");
    return 0;
  }
  arg1 = *argp1; 
  result = sqtpFrameReaderResetStruct(arg1);
  {
    SqtpFrameReader_t * resultptr = (SqtpFrameReader_t *) malloc(sizeof(SqtpFrameReader_t));
    memmove(resultptr, &result, sizeof(SqtpFrameReader_t));
    *(SqtpFrameReader_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameReaderNextStruct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  SqtpFrameReader_t arg1 ;
  SqtpFrameReader_t *argp1 ;
  SqtpFrameReader_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(SqtpFrameReader_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpFrameReader_t");
    return 0;
  }
  arg1 = *argp1; 
  result = sqtpFrameReaderNextStruct(arg1);
  {
    SqtpFrameReader_t * resultptr = (SqtpFrameReader_t *) malloc(sizeof(SqtpFrameReader_t));
    memmove(resultptr, &result, sizeof(SqtpFrameReader_t));
    *(SqtpFrameReader_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterInitStruct(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  size_t arg2 ;
  SqtpFrameWriter_t result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (size_t)jarg2; 
  result = sqtpFrameWriterInitStruct(arg1,arg2);
  {
    SqtpFrameWriter_t * resultptr = (SqtpFrameWriter_t *) malloc(sizeof(SqtpFrameWriter_t));
    memmove(resultptr, &result, sizeof(SqtpFrameWriter_t));
    *(SqtpFrameWriter_t **)&jresult = resultptr;
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterWriteStructDirect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jbyteArray jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  SqtpFrameWriter_t arg1 ;
  SqtpSubframeId_t arg2 ;
  uint8_t *arg3 = (uint8_t *) 0 ;
  size_t arg4 ;
  SqtpFrameWriter_t *argp1 ;
  SqtpFrameWriter_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(SqtpFrameWriter_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpFrameWriter_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (SqtpSubframeId_t)jarg2; 
  {
    arg3 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg3, 0); 
  }
  arg4 = (size_t)jarg4; 
  result = sqtpFrameWriterWriteStructDirect(arg1,arg2,(uint8_t const *)arg3,arg4);
  {
    SqtpFrameWriter_t * resultptr = (SqtpFrameWriter_t *) malloc(sizeof(SqtpFrameWriter_t));
    memmove(resultptr, &result, sizeof(SqtpFrameWriter_t));
    *(SqtpFrameWriter_t **)&jresult = resultptr;
  }
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg3, (jbyte *) arg3, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterWriteStructSubframe(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  SqtpFrameWriter_t arg1 ;
  SqtpSubframe_t arg2 ;
  SqtpFrameWriter_t *argp1 ;
  SqtpSubframe_t *argp2 ;
  SqtpFrameWriter_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  argp1 = *(SqtpFrameWriter_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpFrameWriter_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(SqtpSubframe_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpSubframe_t");
    return 0;
  }
  arg2 = *argp2; 
  result = sqtpFrameWriterWriteStructSubframe(arg1,arg2);
  {
    SqtpFrameWriter_t * resultptr = (SqtpFrameWriter_t *) malloc(sizeof(SqtpFrameWriter_t));
    memmove(resultptr, &result, sizeof(SqtpFrameWriter_t));
    *(SqtpFrameWriter_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_sqtpFrameWriterFinalizeStruct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  SqtpFrameWriter_t arg1 ;
  SqtpFrameWriter_t *argp1 ;
  SqtpFrameWriter_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(SqtpFrameWriter_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SqtpFrameWriter_t");
    return 0;
  }
  arg1 = *argp1; 
  result = sqtpFrameWriterFinalizeStruct(arg1);
  {
    SqtpFrameWriter_t * resultptr = (SqtpFrameWriter_t *) malloc(sizeof(SqtpFrameWriter_t));
    memmove(resultptr, &result, sizeof(SqtpFrameWriter_t));
    *(SqtpFrameWriter_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqspFrameByteArray(JNIEnv *jenv, jclass jcls, jbyteArray jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  jint jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  SqtpFrameWriter_t *arg3 = (SqtpFrameWriter_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  {
    arg1 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg1, 0); 
  }
  arg2 = (int)jarg2; 
  arg3 = *(SqtpFrameWriter_t **)&jarg3; 
  result = (int)SqspFrameByteArray(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg1, (jbyte *) arg1, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SqtpCheckValue_1tSize(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)SqtpCheckValue_tSize();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1SUCCESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_SUCCESS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1FAILED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_FAILED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1FRAME_1END_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_FRAME_END;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1FRAME_1BAD_1FORMAT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_FRAME_BAD_FORMAT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1FRAME_1BAD_1LENGTH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_FRAME_BAD_LENGTH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1FRAME_1BAD_1CHECK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_FRAME_BAD_CHECK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1SUBFRAME_1BAD_1FORMAT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_SUBFRAME_BAD_FORMAT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1SUBFRAME_1BAD_1ID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_SUBFRAME_BAD_ID;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1SUBFRAME_1BAD_1LENGTH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_SUBFRAME_BAD_LENGTH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1STATUS_1SUBFRAME_1BAD_1CHECK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpStatus_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpStatus_e)SQTP_STATUS_SUBFRAME_BAD_CHECK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1RESERVED_10000_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_RESERVED_0000;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1RESERVED_1FFFF_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_RESERVED_FFFF;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1LEGACY_1REQUEST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_LEGACY_REQUEST;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1LEGACY_1RESPONSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_LEGACY_RESPONSE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1RTCM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_RTCM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1OTA_1MTU_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_OTA_MTU;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1OTA_1UPDATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_OTA_UPDATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1OTA_1STATUS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_OTA_STATUS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1RTCM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_RTCM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1STATUS_1COMPACT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_STATUS_COMPACT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1LLA_1COMPACT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_LLA_COMPACT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1LOCAL_1BASE_1CONFIG_1COMPACT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_COMPACT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1RELPOS_1COMPACT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_RELPOS_COMPACT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1HOSTMCU_1STATUS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_HOSTMCU_STATUS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1BLE_1STATUS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_BLE_STATUS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1STATUS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_STATUS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1LLA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_LLA;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1LOCAL_1BASE_1CONFIG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1SITEPOINT_1RELPOS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_SITEPOINT_RELPOS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_SQTP_1ID_1UBLOX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum SqtpSubframeId_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum SqtpSubframeId_e)SQTP_ID_UBLOX;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_sqtp_sqtpJNI_GetSubFrameByteArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  jint jresult = 0 ;
  SqtpFrameReader_t *arg1 = (SqtpFrameReader_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  int arg3 ;
  SqtpStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqtpFrameReader_t **)&jarg1; 
  {
    arg2 = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    arg3 = (*jenv)->GetArrayLength(jenv, jarg2);
  }
  result = (SqtpStatus_t)GetSubFrameByteArray(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

