/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.ntrip;

public class ntrip implements ntripConstants {
  public static NTRIP_Parse_Return_t NTRIP_Parse_Init(NTRIP_Parse_Context_t Context, byte[] JavaByteArray, long length, SWIGTYPE_p_f_enum_NTRIP_Parse_Return_e_enum_NTRIP_Parse_Types_e_p_uint8_t_size_t__void Callback) {
    return NTRIP_Parse_Return_t.swigToEnum(ntripJNI.NTRIP_Parse_Init(NTRIP_Parse_Context_t.getCPtr(Context), Context, JavaByteArray, length, SWIGTYPE_p_f_enum_NTRIP_Parse_Return_e_enum_NTRIP_Parse_Types_e_p_uint8_t_size_t__void.getCPtr(Callback)));
  }

  public static NTRIP_Parse_Return_t NTRIP_Parse(NTRIP_Parse_Context_t Context, byte[] JavaByteArray, long length) {
    return NTRIP_Parse_Return_t.swigToEnum(ntripJNI.NTRIP_Parse(NTRIP_Parse_Context_t.getCPtr(Context), Context, JavaByteArray, length));
  }

  public static NTRIP_Parse_Return_t NTRIP_Parse_Next_Message(NTRIP_Parse_Context_t Context) {
    return NTRIP_Parse_Return_t.swigToEnum(ntripJNI.NTRIP_Parse_Next_Message(NTRIP_Parse_Context_t.getCPtr(Context), Context));
  }

  public static NTRIP_Parse_Return_t NTRIP_GetPoll_Buffer(NTRIP_Parse_Context_t Context, byte[] buffer) {
    return NTRIP_Parse_Return_t.swigToEnum(ntripJNI.NTRIP_GetPoll_Buffer(NTRIP_Parse_Context_t.getCPtr(Context), Context, buffer));
  }

  public static NTRIP_Parse_Return_t NTRIP_GetPoll_Buffer_2(NTRIP_Parse_Context_t Context, byte[] buffer) {
    return NTRIP_Parse_Return_t.swigToEnum(ntripJNI.NTRIP_GetPoll_Buffer_2(NTRIP_Parse_Context_t.getCPtr(Context), Context, buffer));
  }

  public static int getPollIndex(NTRIP_Parse_Context_t context) {
    return ntripJNI.getPollIndex(NTRIP_Parse_Context_t.getCPtr(context), context);
  }

  public static int getRTCMID(byte[] buffer) {
    return ntripJNI.getRTCMID(buffer);
  }

  public static int getRTCMLength(byte[] buffer) {
    return ntripJNI.getRTCMLength(buffer);
  }

  public static int getRTCMCRC(byte[] buffer) {
    return ntripJNI.getRTCMCRC(buffer);
  }

}
