/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.ntrip;

public interface ntripConstants {
  public final static int __STDC_WANT_LIB_EXT1__ = ntripJNI.__STDC_WANT_LIB_EXT1___get();
}
