/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.ntrip;

public final class NTRIP_Version_t {
  public final static NTRIP_Version_t NTRIP_VERSION_UNKNOWN = new NTRIP_Version_t("NTRIP_VERSION_UNKNOWN", ntripJNI.NTRIP_VERSION_UNKNOWN_get());
  public final static NTRIP_Version_t NTRIP_VERSION_1 = new NTRIP_Version_t("NTRIP_VERSION_1");
  public final static NTRIP_Version_t NTRIP_VERSION_2 = new NTRIP_Version_t("NTRIP_VERSION_2");
  public final static NTRIP_Version_t NTRIP_V1 = new NTRIP_Version_t("NTRIP_V1", ntripJNI.NTRIP_V1_get());
  public final static NTRIP_Version_t NTRIP_V2 = new NTRIP_Version_t("NTRIP_V2", ntripJNI.NTRIP_V2_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NTRIP_Version_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NTRIP_Version_t.class + " with value " + swigValue);
  }

  private NTRIP_Version_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NTRIP_Version_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NTRIP_Version_t(String swigName, NTRIP_Version_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NTRIP_Version_t[] swigValues = { NTRIP_VERSION_UNKNOWN, NTRIP_VERSION_1, NTRIP_VERSION_2, NTRIP_V1, NTRIP_V2 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

