/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqtp;

public final class SqtpSubframeId_t {
  public final static SqtpSubframeId_t SQTP_ID_RESERVED_0000 = new SqtpSubframeId_t("SQTP_ID_RESERVED_0000", sqtpJNI.SQTP_ID_RESERVED_0000_get());
  public final static SqtpSubframeId_t SQTP_ID_RESERVED_FFFF = new SqtpSubframeId_t("SQTP_ID_RESERVED_FFFF", sqtpJNI.SQTP_ID_RESERVED_FFFF_get());
  public final static SqtpSubframeId_t SQTP_ID_LEGACY_REQUEST = new SqtpSubframeId_t("SQTP_ID_LEGACY_REQUEST", sqtpJNI.SQTP_ID_LEGACY_REQUEST_get());
  public final static SqtpSubframeId_t SQTP_ID_LEGACY_RESPONSE = new SqtpSubframeId_t("SQTP_ID_LEGACY_RESPONSE", sqtpJNI.SQTP_ID_LEGACY_RESPONSE_get());
  public final static SqtpSubframeId_t SQTP_ID_RTCM = new SqtpSubframeId_t("SQTP_ID_RTCM", sqtpJNI.SQTP_ID_RTCM_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_OTA_MTU = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_OTA_MTU", sqtpJNI.SQTP_ID_SITEPOINT_OTA_MTU_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_OTA_UPDATE = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_OTA_UPDATE", sqtpJNI.SQTP_ID_SITEPOINT_OTA_UPDATE_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_OTA_STATUS = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_OTA_STATUS", sqtpJNI.SQTP_ID_SITEPOINT_OTA_STATUS_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_RTCM = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_RTCM", sqtpJNI.SQTP_ID_SITEPOINT_RTCM_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_STATUS_COMPACT = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_STATUS_COMPACT", sqtpJNI.SQTP_ID_SITEPOINT_STATUS_COMPACT_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_LLA_COMPACT = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_LLA_COMPACT", sqtpJNI.SQTP_ID_SITEPOINT_LLA_COMPACT_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_COMPACT = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_COMPACT", sqtpJNI.SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_COMPACT_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_RELPOS_COMPACT = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_RELPOS_COMPACT", sqtpJNI.SQTP_ID_SITEPOINT_RELPOS_COMPACT_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_HOSTMCU_STATUS = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_HOSTMCU_STATUS", sqtpJNI.SQTP_ID_SITEPOINT_HOSTMCU_STATUS_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_BLE_STATUS = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_BLE_STATUS", sqtpJNI.SQTP_ID_SITEPOINT_BLE_STATUS_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_STATUS = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_STATUS", sqtpJNI.SQTP_ID_SITEPOINT_STATUS_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_LLA = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_LLA", sqtpJNI.SQTP_ID_SITEPOINT_LLA_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG", sqtpJNI.SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_get());
  public final static SqtpSubframeId_t SQTP_ID_SITEPOINT_RELPOS = new SqtpSubframeId_t("SQTP_ID_SITEPOINT_RELPOS", sqtpJNI.SQTP_ID_SITEPOINT_RELPOS_get());
  public final static SqtpSubframeId_t SQTP_ID_UBLOX = new SqtpSubframeId_t("SQTP_ID_UBLOX", sqtpJNI.SQTP_ID_UBLOX_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SqtpSubframeId_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SqtpSubframeId_t.class + " with value " + swigValue);
  }

  private SqtpSubframeId_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SqtpSubframeId_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SqtpSubframeId_t(String swigName, SqtpSubframeId_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SqtpSubframeId_t[] swigValues = { SQTP_ID_RESERVED_0000, SQTP_ID_RESERVED_FFFF, SQTP_ID_LEGACY_REQUEST, SQTP_ID_LEGACY_RESPONSE, SQTP_ID_RTCM, SQTP_ID_SITEPOINT_OTA_MTU, SQTP_ID_SITEPOINT_OTA_UPDATE, SQTP_ID_SITEPOINT_OTA_STATUS, SQTP_ID_SITEPOINT_RTCM, SQTP_ID_SITEPOINT_STATUS_COMPACT, SQTP_ID_SITEPOINT_LLA_COMPACT, SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG_COMPACT, SQTP_ID_SITEPOINT_RELPOS_COMPACT, SQTP_ID_SITEPOINT_HOSTMCU_STATUS, SQTP_ID_SITEPOINT_BLE_STATUS, SQTP_ID_SITEPOINT_STATUS, SQTP_ID_SITEPOINT_LLA, SQTP_ID_SITEPOINT_LOCAL_BASE_CONFIG, SQTP_ID_SITEPOINT_RELPOS, SQTP_ID_UBLOX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

