/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqtp;

public final class SqtpStatus_t {
  public final static SqtpStatus_t SQTP_STATUS_SUCCESS = new SqtpStatus_t("SQTP_STATUS_SUCCESS", sqtpJNI.SQTP_STATUS_SUCCESS_get());
  public final static SqtpStatus_t SQTP_STATUS_FAILED = new SqtpStatus_t("SQTP_STATUS_FAILED", sqtpJNI.SQTP_STATUS_FAILED_get());
  public final static SqtpStatus_t SQTP_STATUS_FRAME_END = new SqtpStatus_t("SQTP_STATUS_FRAME_END", sqtpJNI.SQTP_STATUS_FRAME_END_get());
  public final static SqtpStatus_t SQTP_STATUS_FRAME_BAD_FORMAT = new SqtpStatus_t("SQTP_STATUS_FRAME_BAD_FORMAT", sqtpJNI.SQTP_STATUS_FRAME_BAD_FORMAT_get());
  public final static SqtpStatus_t SQTP_STATUS_FRAME_BAD_LENGTH = new SqtpStatus_t("SQTP_STATUS_FRAME_BAD_LENGTH", sqtpJNI.SQTP_STATUS_FRAME_BAD_LENGTH_get());
  public final static SqtpStatus_t SQTP_STATUS_FRAME_BAD_CHECK = new SqtpStatus_t("SQTP_STATUS_FRAME_BAD_CHECK", sqtpJNI.SQTP_STATUS_FRAME_BAD_CHECK_get());
  public final static SqtpStatus_t SQTP_STATUS_SUBFRAME_BAD_FORMAT = new SqtpStatus_t("SQTP_STATUS_SUBFRAME_BAD_FORMAT", sqtpJNI.SQTP_STATUS_SUBFRAME_BAD_FORMAT_get());
  public final static SqtpStatus_t SQTP_STATUS_SUBFRAME_BAD_ID = new SqtpStatus_t("SQTP_STATUS_SUBFRAME_BAD_ID", sqtpJNI.SQTP_STATUS_SUBFRAME_BAD_ID_get());
  public final static SqtpStatus_t SQTP_STATUS_SUBFRAME_BAD_LENGTH = new SqtpStatus_t("SQTP_STATUS_SUBFRAME_BAD_LENGTH", sqtpJNI.SQTP_STATUS_SUBFRAME_BAD_LENGTH_get());
  public final static SqtpStatus_t SQTP_STATUS_SUBFRAME_BAD_CHECK = new SqtpStatus_t("SQTP_STATUS_SUBFRAME_BAD_CHECK", sqtpJNI.SQTP_STATUS_SUBFRAME_BAD_CHECK_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SqtpStatus_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SqtpStatus_t.class + " with value " + swigValue);
  }

  private SqtpStatus_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SqtpStatus_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SqtpStatus_t(String swigName, SqtpStatus_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SqtpStatus_t[] swigValues = { SQTP_STATUS_SUCCESS, SQTP_STATUS_FAILED, SQTP_STATUS_FRAME_END, SQTP_STATUS_FRAME_BAD_FORMAT, SQTP_STATUS_FRAME_BAD_LENGTH, SQTP_STATUS_FRAME_BAD_CHECK, SQTP_STATUS_SUBFRAME_BAD_FORMAT, SQTP_STATUS_SUBFRAME_BAD_ID, SQTP_STATUS_SUBFRAME_BAD_LENGTH, SQTP_STATUS_SUBFRAME_BAD_CHECK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

