/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqtp;

public class sqtp {
  public static long sqtpFrameGetLength(SWIGTYPE_p_uint8_t buf) {
    return sqtpJNI.sqtpFrameGetLength(SWIGTYPE_p_uint8_t.getCPtr(buf));
  }

  public static SqtpStatus_t sqtpFrameReaderInit(SqtpFrameReader_t fr, byte[] JavaByteArray, long sz) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameReaderInit(SqtpFrameReader_t.getCPtr(fr), fr, JavaByteArray, sz));
  }

  public static SqtpStatus_t sqtpFrameReaderReset(SqtpFrameReader_t fr) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameReaderReset(SqtpFrameReader_t.getCPtr(fr), fr));
  }

  public static SqtpStatus_t sqtpFrameReaderNext(SqtpFrameReader_t fr) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameReaderNext(SqtpFrameReader_t.getCPtr(fr), fr));
  }

  public static SqtpStatus_t sqtpFrameWriterInit(SqtpFrameWriter_t fw, byte[] JavaByteArray, long sz) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameWriterInit(SqtpFrameWriter_t.getCPtr(fw), fw, JavaByteArray, sz));
  }

  public static SqtpStatus_t sqtpFrameWriterReset(SqtpFrameWriter_t fw) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameWriterReset(SqtpFrameWriter_t.getCPtr(fw), fw));
  }

  public static SqtpStatus_t sqtpFrameWriterWriteDirect(SqtpFrameWriter_t fw, SqtpSubframeId_t id, byte[] JavaByteArray, long sz) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameWriterWriteDirect(SqtpFrameWriter_t.getCPtr(fw), fw, id.swigValue(), JavaByteArray, sz));
  }

  public static SqtpStatus_t sqtpFrameWriterWriteSubframe(SqtpFrameWriter_t fw, SqtpSubframe_t sf) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameWriterWriteSubframe(SqtpFrameWriter_t.getCPtr(fw), fw, SqtpSubframe_t.getCPtr(sf), sf));
  }

  public static SqtpStatus_t sqtpFrameWriterFinalize(SqtpFrameWriter_t fw) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.sqtpFrameWriterFinalize(SqtpFrameWriter_t.getCPtr(fw), fw));
  }

  public static SqtpFrameReader_t sqtpFrameReaderInitStruct(byte[] JavaByteArray, long sz) {
    return new SqtpFrameReader_t(sqtpJNI.sqtpFrameReaderInitStruct(JavaByteArray, sz), true);
  }

  public static SqtpFrameReader_t sqtpFrameReaderResetStruct(SqtpFrameReader_t fr) {
    return new SqtpFrameReader_t(sqtpJNI.sqtpFrameReaderResetStruct(SqtpFrameReader_t.getCPtr(fr), fr), true);
  }

  public static SqtpFrameReader_t sqtpFrameReaderNextStruct(SqtpFrameReader_t fr) {
    return new SqtpFrameReader_t(sqtpJNI.sqtpFrameReaderNextStruct(SqtpFrameReader_t.getCPtr(fr), fr), true);
  }

  public static SqtpFrameWriter_t sqtpFrameWriterInitStruct(byte[] JavaByteArray, long sz) {
    return new SqtpFrameWriter_t(sqtpJNI.sqtpFrameWriterInitStruct(JavaByteArray, sz), true);
  }

  public static SqtpFrameWriter_t sqtpFrameWriterWriteStructDirect(SqtpFrameWriter_t fw, SqtpSubframeId_t id, byte[] JavaByteArray, long sz) {
    return new SqtpFrameWriter_t(sqtpJNI.sqtpFrameWriterWriteStructDirect(SqtpFrameWriter_t.getCPtr(fw), fw, id.swigValue(), JavaByteArray, sz), true);
  }

  public static SqtpFrameWriter_t sqtpFrameWriterWriteStructSubframe(SqtpFrameWriter_t fw, SqtpSubframe_t sf) {
    return new SqtpFrameWriter_t(sqtpJNI.sqtpFrameWriterWriteStructSubframe(SqtpFrameWriter_t.getCPtr(fw), fw, SqtpSubframe_t.getCPtr(sf), sf), true);
  }

  public static SqtpFrameWriter_t sqtpFrameWriterFinalizeStruct(SqtpFrameWriter_t fw) {
    return new SqtpFrameWriter_t(sqtpJNI.sqtpFrameWriterFinalizeStruct(SqtpFrameWriter_t.getCPtr(fw), fw), true);
  }

  public static int SqspFrameByteArray(byte[] JavaByteArray, int Length, SqtpFrameWriter_t FW) {
    return sqtpJNI.SqspFrameByteArray(JavaByteArray, Length, SqtpFrameWriter_t.getCPtr(FW), FW);
  }

  public static int SqtpCheckValue_tSize() {
    return sqtpJNI.SqtpCheckValue_tSize();
  }

  public static SqtpStatus_t GetSubFrameByteArray(SqtpFrameReader_t Reader, byte[] buffer) {
    return SqtpStatus_t.swigToEnum(sqtpJNI.GetSubFrameByteArray(SqtpFrameReader_t.getCPtr(Reader), Reader, buffer));
  }

}
