/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.signalquest.swig.sqtp;

public class SqtpSubframe_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SqtpSubframe_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SqtpSubframe_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SqtpSubframe_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sqtpJNI.delete_SqtpSubframe_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPayload(SWIGTYPE_p_uint8_t value) {
    sqtpJNI.SqtpSubframe_t_payload_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPayload() {
    long cPtr = sqtpJNI.SqtpSubframe_t_payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setId(SqtpSubframeId_t value) {
    sqtpJNI.SqtpSubframe_t_id_set(swigCPtr, this, value.swigValue());
  }

  public SqtpSubframeId_t getId() {
    return SqtpSubframeId_t.swigToEnum(sqtpJNI.SqtpSubframe_t_id_get(swigCPtr, this));
  }

  public void setLength(long value) {
    sqtpJNI.SqtpSubframe_t_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return sqtpJNI.SqtpSubframe_t_length_get(swigCPtr, this);
  }

  public SqtpSubframe_t() {
    this(sqtpJNI.new_SqtpSubframe_t(), true);
  }

}
