/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#include "NTRIPBuffer.h"

// NTRIP_GetPoll_Buffer() is optional, no longer needed, can use "Arrays.copyOf(PollBuffer, (int) poll.getLength());" or similar
//NTRIP_Parse_Return_t	NTRIP_GetPoll_Buffer(NTRIP_Parse_Context_t* Context, uint8_t *JavaByteArray, int MaxLength)
NTRIP_Parse_Return_t	NTRIP_GetPoll_Buffer(NTRIP_Parse_Context_t* Context, uint8_t *buffer, int length)
{
    NTRIP_Parse_Poll_t *P = &(Context->Poll);

    if( P->Status != NTRIP_MESSAGE_PENDING)  return(P->Status);
    if( P->Buffer == NULL)  return(NTRIP_NO_BUFFER);
    if( P->Length == 0)  return(NTRIP_NO_BUFFER);
//    if( P->Length > MaxLength)  return(NTRIP_BUFFER_OVERRUN);
    if( P->Length > length)  return(NTRIP_BUFFER_OVERRUN);

//    for(int i=0; i< P->Length; i++)
//        JavaByteArray[i] = P->Buffer[i];
    for(int i=0; i< P->Length; i++)
        buffer[i] = P->Buffer[i];
//TODO: Need to return Length! To MaxLength?
    return(P->Status);
}

//Testing...
//NTRIP_Parse_Return_t	NTRIP_GetPoll_Buffer_2(NTRIP_Parse_Context_t* Context, uint8_t *JavaByteArray, int MaxLength)
NTRIP_Parse_Return_t	NTRIP_GetPoll_Buffer_2(NTRIP_Parse_Context_t* Context, uint8_t *buffer, int length)
{
    NTRIP_Parse_Poll_t *P = &(Context->Poll);

    if( P->Status != NTRIP_MESSAGE_PENDING)  return(P->Status);
    if( P->Buffer == NULL)  return(NTRIP_NO_BUFFER);
    if( P->Length == 0)  return(NTRIP_NO_BUFFER);
//    if( P->Length > MaxLength)  return(NTRIP_BUFFER_OVERRUN);
    if( P->Length > length)  return(NTRIP_BUFFER_OVERRUN);

//    for(int i=0; i< P->Length; i++)
//        JavaByteArray[i] = P->Buffer[i];
    for(int i=0; i< P->Length; i++)
        buffer[i] = P->Buffer[i];

    return(P->Status);
}

////unsigned char (*)[7]
//uint8_t *getAccel_2()   //ought to declare size of returned byte[] array here, but typemaps declare it.
//{
//    static  uint8_t x[8] = {1,2,3}; //Needs to be static? Not allocated off stack? or Global? Or?
////    uint8_t x[8] = {1,2,3};  //NOTE: size returned need to match typemaps below  // size not declared here, lets' see what breaks with mismatch between size declared in typemaps and here.
//
//    x[0] = 0;
//    x[1] = 1;
//
//    x[4] = 7;   //This might/should break something since x isn't big enough!
//
//    return((uint8_t *)(&x));
//}
//
//
//uint8_t *getAccel_3(uint8_t *buffer, int length)
//{
//    static  uint8_t x[] = {1,2,3,4};
//
//    x[3] = 5;
//    x[2] = buffer[0];
//    x[1] = buffer[1];
//    x[0] = buffer[2];
//
////    return(&x);
//    return((uint8_t *)(&x));
//}
//
//char *getFirst_HTTP_Reply()
//{
//    static const char string[] = "Hello!";
//
//    return(&string);
////    return("Hello!");
//}
//
//char *getFirst_HTTP_Reply2(NTRIP_Header_Info_t *header)
//{
//    static const char string[] = "Hello!";
//
//
////    return("Hello!");
////    return(&string);
//    return(header->First_HTTP_Reply);
//}
//
////'char* myFunc2(void)' returns a Java String   https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html#modified_utf_8_strings
//char* myFunc2(void) //'char* myFunc2(void)' returns a Java String
//{
//    return("Hello!");   //implicitly static and constant
//}

int getPollIndex(NTRIP_Parse_Context_t *context)
{
    if(context == NULL)  return(0); // Do no harm

    if(context->WorkingBuffer == NULL)  return(0); // Do no harm
    if(context->Poll.Buffer == NULL)  return(0); // Do no harm
    if(((context->Poll.Buffer - context->WorkingBuffer)) < 0)  return(0); // Do no harm
    if(((context->Poll.Buffer - context->WorkingBuffer)) > context->Length)  return(0); // Do no harm

    int Index = (context->Poll.Buffer - context->WorkingBuffer);

    return(Index);
}

int getRTCMID(uint8_t *buffer, int length)
{
//    uint16_t RTCM_ID = ((data->om_data[3] << 4) | (data->om_data[4] >> 4));

    if(length < (4+1))  return -1;  //  BAD LENGTH

    uint16_t RTCM_ID = ((buffer[3] << 4) | (buffer[4] >> 4)) & 0x0FFF;  // 12 bit ID's
    // Consider returning Sub ID's? In a different function?

    return((int)RTCM_ID);
}

int getRTCMLength(uint8_t *buffer, int length)
{
//    uint16_t Length  = (((data->om_data[1] & 0x03) << 8) | data->om_data[2]);

    if(length < (2+1))  return -1;  //  BAD LENGTH

    uint16_t RTCMLength = (((buffer[1] & 0x03) << 8) | buffer[2]);

    return((int)RTCMLength);
}

int getRTCMCRC(uint8_t *buffer, int length)
{
//    uint32_t MsgCRC  = (((uint32_t)data->om_data[3 + Length] << 16) | (data->om_data[3 + Length + 1] << 8) | data->om_data[3 + Length + 2]);

    if(length < (2+1))  return -1;  //  BAD LENGTH

    uint16_t RTCMLength = (((buffer[1] & 0x03) << 8) | buffer[2]);

    if(length < (3 + RTCMLength + 3))  return -1;  //  BAD LENGTH

    uint32_t MsgCRC = (((uint32_t)buffer[3 + RTCMLength] << 16) | (buffer[3 + RTCMLength + 1] << 8) | buffer[3 + RTCMLength + 2]);

    return(MsgCRC);
}




#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI__1_1STDC_1WANT_1LIB_1EXT1_1_1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1BAD_1HEADER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_BAD_HEADER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1UNEXPECTED_1CALLBACK_1FUNCTION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_UNEXPECTED_CALLBACK_FUNCTION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1UNKNOWN_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_UNKNOWN_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1NO_1CONTEXT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_NO_CONTEXT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1BUFFER_1OVERRUN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_BUFFER_OVERRUN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1BAD_1CRC24Q_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_BAD_CRC24Q;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1BUFFER_1TOO_1SMALL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_BUFFER_TOO_SMALL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1BAD_1PREAMBLE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_BAD_PREAMBLE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1NO_1BUFFER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_NO_BUFFER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1NO_1CALLBACK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_NO_CALLBACK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1NOT_1ENOUGH_1ROOM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_NOT_ENOUGH_ROOM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1FULL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_FULL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1NOT_1INITIALIZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_NOT_INITIALIZED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1SUCCESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_SUCCESS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1MESSAGE_1PENDING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Return_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Return_e)NTRIP_MESSAGE_PENDING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1RTCM_1Message_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Types_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Types_e)NTRIP_RTCM_Message;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1V1_1Header_1Message_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Types_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Types_e)NTRIP_V1_Header_Message;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1V2_1Header_1Message_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Types_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Types_e)NTRIP_V2_Header_Message;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1INIT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Parse_Context_State_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Parse_Context_State_e)NTRIP_INIT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  NTRIP_Parse_Return_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  arg2 = (NTRIP_Parse_Return_t)jarg2; 
  if (arg1) (arg1)->Status = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  result = (NTRIP_Parse_Return_t) ((arg1)->Status);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  NTRIP_Parse_Types_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  arg2 = (NTRIP_Parse_Types_t)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  NTRIP_Parse_Types_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  result = (NTRIP_Parse_Types_t) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Buffer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Buffer = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Buffer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Buffer);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->Length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Poll_1t_1Length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  result =  ((arg1)->Length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_new_1NTRIP_1Parse_1Poll_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Poll_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct NTRIP_Parse_Poll_s *)calloc(1, sizeof(struct NTRIP_Parse_Poll_s));
  *(struct NTRIP_Parse_Poll_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_delete_1NTRIP_1Parse_1Poll_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct NTRIP_Parse_Poll_s *arg1 = (struct NTRIP_Parse_Poll_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct NTRIP_Parse_Poll_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1Unknown_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_Unknown;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_10_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1200_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_200;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1401_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_401;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1404_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_404;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1409_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_409;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1500_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_500;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1501_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_501;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_Error_1Status_1503_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum Error_Status_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum Error_Status_e)Error_Status_503;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Error_1Status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  Error_Status_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = (Error_Status_t)jarg2; 
  if (arg1) (arg1)->Error_Status = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Error_1Status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  Error_Status_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (Error_Status_t) ((arg1)->Error_Status);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorized_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->Authorized = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorized_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (bool) ((arg1)->Authorized);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Code = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Code);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Short_1Text_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Short_Text = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Short_1Text_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Short_Text);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Description_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Description = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Description_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Description);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1First_1HTTP_1Reply_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->First_HTTP_Reply = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1First_1HTTP_1Reply_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->First_HTTP_Reply);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorization_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Authorization = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorization_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Authorization);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Cache_1Control_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Cache_Control = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Cache_1Control_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Cache_Control);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Connection_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Connection = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Connection_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Connection);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Content_Length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Content_Length);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Content_Type = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Content_Type);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Date_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Date = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Date_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Date);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Host_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Host = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Host_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Host);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Server_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Server = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Server_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Server);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Pragma_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Pragma = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Pragma_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Pragma);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Transfer_1Encoding_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Transfer_Encoding = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Transfer_1Encoding_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Transfer_Encoding);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1WWW_1Authenticate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->WWW_Authenticate = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1WWW_1Authenticate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->WWW_Authenticate);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Ntrip_Version = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Ntrip_Version);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Flags_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Ntrip_Flags = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Flags_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Ntrip_Flags);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Code_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Code_string, (const char *)arg2, 64-1);
      arg1->Code_string[64-1] = 0;
    } else {
      arg1->Code_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Code_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Code_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Short_1Text_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Short_Text_string, (const char *)arg2, 64-1);
      arg1->Short_Text_string[64-1] = 0;
    } else {
      arg1->Short_Text_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Short_1Text_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Short_Text_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Description_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Description_string, (const char *)arg2, 64-1);
      arg1->Description_string[64-1] = 0;
    } else {
      arg1->Description_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Description_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Description_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1First_1HTTP_1Reply_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->First_HTTP_Reply_string, (const char *)arg2, 64-1);
      arg1->First_HTTP_Reply_string[64-1] = 0;
    } else {
      arg1->First_HTTP_Reply_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1First_1HTTP_1Reply_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->First_HTTP_Reply_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorization_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Authorization_string, (const char *)arg2, 64-1);
      arg1->Authorization_string[64-1] = 0;
    } else {
      arg1->Authorization_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Authorization_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Authorization_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Cache_1Control_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Cache_Control_string, (const char *)arg2, 64-1);
      arg1->Cache_Control_string[64-1] = 0;
    } else {
      arg1->Cache_Control_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Cache_1Control_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Cache_Control_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Connection_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Connection_string, (const char *)arg2, 64-1);
      arg1->Connection_string[64-1] = 0;
    } else {
      arg1->Connection_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Connection_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Connection_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Length_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Content_Length_string, (const char *)arg2, 64-1);
      arg1->Content_Length_string[64-1] = 0;
    } else {
      arg1->Content_Length_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Length_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Content_Length_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Type_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Content_Type_string, (const char *)arg2, 64-1);
      arg1->Content_Type_string[64-1] = 0;
    } else {
      arg1->Content_Type_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Content_1Type_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Content_Type_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Date_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Date_string, (const char *)arg2, 64-1);
      arg1->Date_string[64-1] = 0;
    } else {
      arg1->Date_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Date_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Date_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Host_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Host_string, (const char *)arg2, 64-1);
      arg1->Host_string[64-1] = 0;
    } else {
      arg1->Host_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Host_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Host_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Server_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Server_string, (const char *)arg2, 64-1);
      arg1->Server_string[64-1] = 0;
    } else {
      arg1->Server_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Server_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Server_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Pragma_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Pragma_string, (const char *)arg2, 64-1);
      arg1->Pragma_string[64-1] = 0;
    } else {
      arg1->Pragma_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Pragma_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Pragma_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Transfer_1Encoding_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Transfer_Encoding_string, (const char *)arg2, 64-1);
      arg1->Transfer_Encoding_string[64-1] = 0;
    } else {
      arg1->Transfer_Encoding_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Transfer_1Encoding_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Transfer_Encoding_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1WWW_1Authenticate_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->WWW_Authenticate_string, (const char *)arg2, 64-1);
      arg1->WWW_Authenticate_string[64-1] = 0;
    } else {
      arg1->WWW_Authenticate_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1WWW_1Authenticate_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->WWW_Authenticate_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Version_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Ntrip_Version_string, (const char *)arg2, 64-1);
      arg1->Ntrip_Version_string[64-1] = 0;
    } else {
      arg1->Ntrip_Version_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Version_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Ntrip_Version_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Flags_1string_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *arg2 = (char *) (char *)0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->Ntrip_Flags_string, (const char *)arg2, 64-1);
      arg1->Ntrip_Flags_string[64-1] = 0;
    } else {
      arg1->Ntrip_Flags_string[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Header_1Info_1t_1Ntrip_1Flags_1string_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  result = (char *)(char *) ((arg1)->Ntrip_Flags_string);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_new_1NTRIP_1Header_1Info_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct NTRIP_Header_Info_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct NTRIP_Header_Info_s *)calloc(1, sizeof(struct NTRIP_Header_Info_s));
  *(struct NTRIP_Header_Info_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_delete_1NTRIP_1Header_1Info_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct NTRIP_Header_Info_s *arg1 = (struct NTRIP_Header_Info_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct NTRIP_Header_Info_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1VERSION_1UNKNOWN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Version_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Version_e)NTRIP_VERSION_UNKNOWN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1V1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Version_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Version_e)NTRIP_V1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1V2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum NTRIP_Version_e result;
  
  (void)jenv;
  (void)jcls;
  result = (enum NTRIP_Version_e)NTRIP_V2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1CallBack_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Call_Back_t *arg2 = (NTRIP_Parse_Call_Back_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(NTRIP_Parse_Call_Back_t **)&jarg2; 
  if (arg1) (arg1)->CallBack = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1CallBack_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Call_Back_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Parse_Call_Back_t *) ((arg1)->CallBack);
  *(NTRIP_Parse_Call_Back_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1WorkingBuffer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->WorkingBuffer = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1WorkingBuffer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->WorkingBuffer);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->Length = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result =  ((arg1)->Length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1State_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Context_State_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (NTRIP_Parse_Context_State_t)jarg2; 
  if (arg1) (arg1)->State = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1State_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Context_State_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Parse_Context_State_t) ((arg1)->State);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Last_1State_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Context_State_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (NTRIP_Parse_Context_State_t)jarg2; 
  if (arg1) (arg1)->Last_State = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Last_1State_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Context_State_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Parse_Context_State_t) ((arg1)->Last_State);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Head_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Head = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Head_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Head);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Tail_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Tail = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Tail_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Tail);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Wptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Wptr = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Wptr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Wptr);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Bptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->Bptr = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Bptr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->Bptr);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1End_1of_1Chunk_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->End_of_Chunk = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1End_1of_1Chunk_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (uint8_t *) ((arg1)->End_of_Chunk);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Count = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (int) ((arg1)->Count);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Free_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Free = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Free_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (int) ((arg1)->Free);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1ChunkSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ChunkSize = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1ChunkSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (int) ((arg1)->ChunkSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1chunked_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->chunked = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1chunked_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (bool) ((arg1)->chunked);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Last_1Return_1Value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Return_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (NTRIP_Parse_Return_t)jarg2; 
  if (arg1) (arg1)->Last_Return_Value = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Last_1Return_1Value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Parse_Return_t) ((arg1)->Last_Return_Value);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1NTRIP_1Version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Version_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = (NTRIP_Version_t)jarg2; 
  if (arg1) (arg1)->NTRIP_Version = arg2;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1NTRIP_1Version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Version_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Version_t) ((arg1)->NTRIP_Version);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Poll_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Poll_t *arg2 = (NTRIP_Parse_Poll_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(NTRIP_Parse_Poll_t **)&jarg2; 
  if (arg1) (arg1)->Poll = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Poll_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Parse_Poll_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Parse_Poll_t *)& ((arg1)->Poll);
  *(NTRIP_Parse_Poll_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Header_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Header_Info_t *arg2 = (NTRIP_Header_Info_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  arg2 = *(NTRIP_Header_Info_t **)&jarg2; 
  if (arg1) (arg1)->Header = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Context_1t_1Header_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  NTRIP_Header_Info_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  result = (NTRIP_Header_Info_t *)& ((arg1)->Header);
  *(NTRIP_Header_Info_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_new_1NTRIP_1Parse_1Context_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct NTRIP_Parse_Context_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct NTRIP_Parse_Context_s *)calloc(1, sizeof(struct NTRIP_Parse_Context_s));
  *(struct NTRIP_Parse_Context_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_delete_1NTRIP_1Parse_1Context_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct NTRIP_Parse_Context_s *arg1 = (struct NTRIP_Parse_Context_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct NTRIP_Parse_Context_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  NTRIP_Parse_Call_Back_t *arg4 = (NTRIP_Parse_Call_Back_t *) 0 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (size_t)jarg3; 
  arg4 = *(NTRIP_Parse_Call_Back_t **)&jarg4; 
  result = (NTRIP_Parse_Return_t)NTRIP_Parse_Init(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  size_t arg3 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  {
    arg2 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg2, 0); 
  }
  arg3 = (size_t)jarg3; 
  result = (NTRIP_Parse_Return_t)NTRIP_Parse(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (jbyte *) arg2, 0); 
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1Parse_1Next_1Message(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  result = (NTRIP_Parse_Return_t)NTRIP_Parse_Next_Message(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1GetPoll_1Buffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  int arg3 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  {
    arg2 = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    arg3 = (*jenv)->GetArrayLength(jenv, jarg2);
  }
  result = (NTRIP_Parse_Return_t)NTRIP_GetPoll_Buffer(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_NTRIP_1GetPoll_1Buffer_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  int arg3 ;
  NTRIP_Parse_Return_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  {
    arg2 = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    arg3 = (*jenv)->GetArrayLength(jenv, jarg2);
  }
  result = (NTRIP_Parse_Return_t)NTRIP_GetPoll_Buffer_2(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_getPollIndex(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  NTRIP_Parse_Context_t *arg1 = (NTRIP_Parse_Context_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NTRIP_Parse_Context_t **)&jarg1; 
  result = (int)getPollIndex(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_getRTCMID(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  jint jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (*jenv)->GetByteArrayElements(jenv, jarg1, NULL);
    arg2 = (*jenv)->GetArrayLength(jenv, jarg1);
  }
  result = (int)getRTCMID(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_getRTCMLength(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  jint jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (*jenv)->GetByteArrayElements(jenv, jarg1, NULL);
    arg2 = (*jenv)->GetArrayLength(jenv, jarg1);
  }
  result = (int)getRTCMLength(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_signalquest_swig_ntrip_ntripJNI_getRTCMCRC(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  jint jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (*jenv)->GetByteArrayElements(jenv, jarg1, NULL);
    arg2 = (*jenv)->GetArrayLength(jenv, jarg1);
  }
  result = (int)getRTCMCRC(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

